import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "api/search/search-api",
    },
    {
      type: "category",
      label: "Global",
      link: {
        type: "doc",
        id: "api/search/search-global",
      },
      items: [
        {
          type: "doc",
          id: "api/search/global-search-v-2",
          label: "Global multi-entity search (v2)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/search/global-search",
          label: "Global multi-entity search",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/search/search-scan",
          label: "Quick search for tickets, assets, and users",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "History",
      link: {
        type: "doc",
        id: "api/search/search-history",
      },
      items: [
        {
          type: "doc",
          id: "api/search/get-recent-searches",
          label: "Retrieve recent search history",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Schemas",
      items: [
        {
          type: "doc",
          id: "api/search/schemas/address",
          label: "Address",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/app",
          label: "App",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/appmodelissue",
          label: "AppModelIssue",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/asset",
          label: "Asset",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/assetcategorysummary",
          label: "AssetCategorySummary",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/assetcustomfieldvalue",
          label: "AssetCustomFieldValue",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/assetdatamappinglookup",
          label: "AssetDataMappingLookup",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/assetdatamappingsource",
          label: "AssetDataMappingSource",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/assetdatamappings",
          label: "AssetDataMappings",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/assetfundingtype",
          label: "AssetFundingType",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/assetinventorytype",
          label: "AssetInventoryType",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/assetmanufacturersummary",
          label: "AssetManufacturerSummary",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/assetmodelsummary",
          label: "AssetModelSummary",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/assetownersummary",
          label: "AssetOwnerSummary",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/assetstatussummary",
          label: "AssetStatusSummary",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/assetstatustype",
          label: "AssetStatusType",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/assettotalcost",
          label: "AssetTotalCost",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/assettype",
          label: "AssetType",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/assetvaluation",
          label: "AssetValuation",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/assetvaluationperiod",
          label: "AssetValuationPeriod",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/category",
          label: "Category",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/closereason",
          label: "CloseReason",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/closereasontype",
          label: "CloseReasonType",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/complexeditorvalues",
          label: "ComplexEditorValues",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/customfieldeditortypeid",
          label: "CustomFieldEditorTypeId",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/customfieldtypedetail",
          label: "CustomFieldTypeDetail",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/customfieldvalue",
          label: "CustomFieldValue",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/department",
          label: "Department",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/employmentstatus",
          label: "EmploymentStatus",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/file",
          label: "File",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/filemetadata",
          label: "FileMetaData",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/filemetadataazurevideo",
          label: "FileMetaDataAzureVideo",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/filetype",
          label: "FileType",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/forbiddenerror",
          label: "ForbiddenError",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/globalsearchdatasource",
          label: "GlobalSearchDataSource",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/globalsearchfacetbitmask",
          label: "GlobalSearchFacetBitmask",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/globalsearchrequest",
          label: "GlobalSearchRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/globalsearchresponse",
          label: "GlobalSearchResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/globalsearchresultitem",
          label: "GlobalSearchResultItem",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/helpfulnessstat",
          label: "HelpfulnessStat",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/internalservererror",
          label: "InternalServerError",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/issue",
          label: "Issue",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/kbarticle",
          label: "KbArticle",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/kbarticlecustomfieldvalue",
          label: "KbArticleCustomFieldValue",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/laborrateactivity",
          label: "LaborRateActivity",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/listgetresponse",
          label: "ListGetResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/location",
          label: "Location",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/locationcustomfieldvalue",
          label: "LocationCustomFieldValue",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/locationroom",
          label: "LocationRoom",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/locationroomavailabletime",
          label: "LocationRoomAvailableTime",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/locationroomcustomfieldvalue",
          label: "LocationRoomCustomFieldValue",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/locationroomtype",
          label: "LocationRoomType",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/locationstatustype",
          label: "LocationStatusType",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/locationtype",
          label: "LocationType",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/manufacturer",
          label: "Manufacturer",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/manufacturerscope",
          label: "ManufacturerScope",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/metric",
          label: "Metric",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/model",
          label: "Model",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/modelissue",
          label: "ModelIssue",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/pagingmetadata",
          label: "PagingMetadata",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/producttier",
          label: "ProductTier",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/purchaseorderstatustype",
          label: "PurchaseOrderStatusType",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/recentusersearch",
          label: "RecentUserSearch",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/recentusersearchlistresponse",
          label: "RecentUserSearchListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/role",
          label: "Role",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/searchlistresponse",
          label: "SearchListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/searchresult",
          label: "SearchResult",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/simpleuser",
          label: "SimpleUser",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/site",
          label: "Site",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/siteapphook",
          label: "SiteAppHook",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/siteappsconfiguration",
          label: "SiteAppsConfiguration",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/siteconfigurationsetting",
          label: "SiteConfigurationSetting",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/sitekpi",
          label: "SiteKpi",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/sitesettings",
          label: "SiteSettings",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/sitestatus",
          label: "SiteStatus",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/sitestatustype",
          label: "SiteStatusType",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/sla",
          label: "Sla",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/softvalidationerror",
          label: "SoftValidationError",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/source",
          label: "Source",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/tag",
          label: "Tag",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/team",
          label: "Team",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/ticket",
          label: "Ticket",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/ticketactivity",
          label: "TicketActivity",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/ticketadditionaldetails",
          label: "TicketAdditionalDetails",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/ticketasset",
          label: "TicketAsset",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/ticketlocationsummary",
          label: "TicketLocationSummary",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/ticketpermission",
          label: "TicketPermission",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/ticketprioritylevel",
          label: "TicketPriorityLevel",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/ticketsearchfacetkey",
          label: "TicketSearchFacetKey",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/ticketsearchfilter",
          label: "TicketSearchFilter",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/ticketsubtask",
          label: "TicketSubtask",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/ticketusersummary",
          label: "TicketUserSummary",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/ticketworkflowstepsummary",
          label: "TicketWorkflowStepSummary",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/unauthorizederror",
          label: "UnauthorizedError",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/user",
          label: "User",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/usercustomfieldvalue",
          label: "UserCustomFieldValue",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/userdatamappinglookup",
          label: "UserDataMappingLookup",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/userdatamappingsource",
          label: "UserDataMappingSource",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/userdatamappings",
          label: "UserDataMappings",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/usernotificationsettings",
          label: "UserNotificationSettings",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/useroptions",
          label: "UserOptions",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/useroptionslocations",
          label: "UserOptionsLocations",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/userpermissions",
          label: "UserPermissions",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/usersummary",
          label: "UserSummary",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/validationerror",
          label: "ValidationError",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/search/schemas/view",
          label: "View",
          className: "schema",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
