import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// Import generated API sidebars
// These are auto-generated by docusaurus-plugin-openapi-docs

const sidebars: SidebarsConfig = {
  // Getting started and guides sidebar
  guideSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Authentication',
      collapsed: false,
      items: [
        'guides/authentication',
        'guides/api-tokens',
      ],
    },
    {
      type: 'category',
      label: 'Core Concepts',
      items: [
        'guides/pagination',
        'guides/filtering',
        'guides/error-handling',
      ],
    },
    {
      type: 'category',
      label: 'Common Workflows',
      items: [
        'guides/working-with-tickets',
        'guides/working-with-assets',
      ],
    },
  ],

  // API Reference sidebar - dynamically imports generated sidebars
  apiSidebar: [
    {
      type: 'doc',
      id: 'api/index',
      label: 'API Overview',
    },
    {
      type: 'category',
      label: 'Tickets',
      collapsed: true,
      items: require('./docs/api/tickets/sidebar.ts').default,
    },
    {
      type: 'category',
      label: 'Assets',
      collapsed: true,
      items: require('./docs/api/assets/sidebar.ts').default,
    },
    {
      type: 'category',
      label: 'Users',
      collapsed: true,
      items: require('./docs/api/users/sidebar.ts').default,
    },
    {
      type: 'category',
      label: 'Locations',
      collapsed: true,
      items: require('./docs/api/locations/sidebar.ts').default,
    },
    {
      type: 'category',
      label: 'Custom Fields',
      collapsed: true,
      items: require('./docs/api/custom-fields/sidebar.ts').default,
    },
    {
      type: 'category',
      label: 'Categories',
      collapsed: true,
      items: require('./docs/api/categories/sidebar.ts').default,
    },
    {
      type: 'category',
      label: 'Workflows',
      collapsed: true,
      items: require('./docs/api/workflows/sidebar.ts').default,
    },
    {
      type: 'category',
      label: 'Events',
      collapsed: true,
      items: require('./docs/api/events/sidebar.ts').default,
    },
    {
      type: 'category',
      label: 'Inventory',
      collapsed: true,
      items: require('./docs/api/inventory/sidebar.ts').default,
    },
    {
      type: 'category',
      label: 'Parts',
      collapsed: true,
      items: require('./docs/api/parts/sidebar.ts').default,
    },
    {
      type: 'category',
      label: 'Organizations',
      collapsed: true,
      items: require('./docs/api/organizations/sidebar.ts').default,
    },
    {
      type: 'category',
      label: 'Teams',
      collapsed: true,
      items: require('./docs/api/teams/sidebar.ts').default,
    },
    {
      type: 'category',
      label: 'Files',
      collapsed: true,
      items: require('./docs/api/files/sidebar.ts').default,
    },
    {
      type: 'category',
      label: 'Filters',
      collapsed: true,
      items: require('./docs/api/filters/sidebar.ts').default,
    },
    {
      type: 'category',
      label: 'Search',
      collapsed: true,
      items: require('./docs/api/search/sidebar.ts').default,
    },
    {
      type: 'category',
      label: 'Other APIs',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Analytics',
          items: require('./docs/api/analytics/sidebar.ts').default,
        },
        {
          type: 'category',
          label: 'Funding Sources',
          items: require('./docs/api/funding-sources/sidebar.ts').default,
        },
        {
          type: 'category',
          label: 'Invoicing',
          items: require('./docs/api/invoicing/sidebar.ts').default,
        },
        {
          type: 'category',
          label: 'Issues',
          items: require('./docs/api/issues/sidebar.ts').default,
        },
        {
          type: 'category',
          label: 'Manufacturers',
          items: require('./docs/api/manufacturers/sidebar.ts').default,
        },
        {
          type: 'category',
          label: 'Model Issues',
          items: require('./docs/api/model-issues/sidebar.ts').default,
        },
        {
          type: 'category',
          label: 'Sites',
          items: require('./docs/api/sites/sidebar.ts').default,
        },
        {
          type: 'category',
          label: 'SLAs',
          items: require('./docs/api/slas/sidebar.ts').default,
        },
        {
          type: 'category',
          label: 'Suppliers',
          items: require('./docs/api/suppliers/sidebar.ts').default,
        },
        {
          type: 'category',
          label: 'Surveys',
          items: require('./docs/api/surveys/sidebar.ts').default,
        },
        {
          type: 'category',
          label: 'Tags',
          items: require('./docs/api/tags/sidebar.ts').default,
        },
        {
          type: 'category',
          label: 'Views',
          items: require('./docs/api/views/sidebar.ts').default,
        },
      ],
    },
  ],
};

export default sidebars;
