import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// Import generated API sidebars
// These are auto-generated by docusaurus-plugin-openapi-docs

// Helper to extract intro page as category link and filter it from items
// This puts the overview content on the category landing page instead of a separate "Introduction" page
function extractCategoryWithIntro(sidebarItems: any[]) {
  // The first item is typically the intro/info page (e.g., "tickets-api")
  const introItem = sidebarItems.find(item => item.type === 'doc' && item.id?.endsWith('-api'));
  const otherItems = sidebarItems.filter(item => !(item.type === 'doc' && item.id?.endsWith('-api')));

  return {
    link: introItem ? { type: 'doc' as const, id: introItem.id } : undefined,
    items: otherItems,
  };
}

const sidebars: SidebarsConfig = {
  // Getting started and guides sidebar
  guideSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'guides/authentication',
        'guides/popular-apis',
        'guides/products-sites-workspaces',
      ],
    },
    {
      type: 'category',
      label: 'Core Concepts',
      items: [
        'guides/pagination',
        'guides/filtering',
        'guides/error-handling',
      ],
    },
    {
      type: 'category',
      label: 'Working with Data',
      items: [
        'guides/working-with-tickets',
        'guides/ticket-activities',
        'guides/working-with-assets',
      ],
    },
    {
      type: 'category',
      label: 'Integration',
      items: [
        'guides/webhooks',
        'guides/support',
      ],
    },
  ],

  // API Reference sidebar - dynamically imports generated sidebars
  // All 27 API categories flattened at top level, sorted alphabetically
  // Uses extractCategoryWithIntro to put overview content on category page instead of separate "Introduction" item
  apiSidebar: [
    {
      type: 'doc',
      id: 'api/index',
      label: 'API Overview',
    },
    {
      type: 'category',
      label: 'Analytics',
      collapsed: true,
      ...extractCategoryWithIntro(require('./docs/api/analytics/sidebar.ts').default),
    },
    {
      type: 'category',
      label: 'Assets',
      collapsed: true,
      ...extractCategoryWithIntro(require('./docs/api/assets/sidebar.ts').default),
    },
    {
      type: 'category',
      label: 'Categories',
      collapsed: true,
      ...extractCategoryWithIntro(require('./docs/api/categories/sidebar.ts').default),
    },
    {
      type: 'category',
      label: 'Custom Fields',
      collapsed: true,
      ...extractCategoryWithIntro(require('./docs/api/custom-fields/sidebar.ts').default),
    },
    {
      type: 'category',
      label: 'Events',
      collapsed: true,
      ...extractCategoryWithIntro(require('./docs/api/events/sidebar.ts').default),
    },
    {
      type: 'category',
      label: 'Files',
      collapsed: true,
      ...extractCategoryWithIntro(require('./docs/api/files/sidebar.ts').default),
    },
    {
      type: 'category',
      label: 'Filters',
      collapsed: true,
      ...extractCategoryWithIntro(require('./docs/api/filters/sidebar.ts').default),
    },
    {
      type: 'category',
      label: 'Funding Sources',
      collapsed: true,
      ...extractCategoryWithIntro(require('./docs/api/funding-sources/sidebar.ts').default),
    },
    {
      type: 'category',
      label: 'Inventory',
      collapsed: true,
      ...extractCategoryWithIntro(require('./docs/api/inventory/sidebar.ts').default),
    },
    {
      type: 'category',
      label: 'Invoicing',
      collapsed: true,
      ...extractCategoryWithIntro(require('./docs/api/invoicing/sidebar.ts').default),
    },
    {
      type: 'category',
      label: 'Issues',
      collapsed: true,
      ...extractCategoryWithIntro(require('./docs/api/issues/sidebar.ts').default),
    },
    {
      type: 'category',
      label: 'Locations',
      collapsed: true,
      ...extractCategoryWithIntro(require('./docs/api/locations/sidebar.ts').default),
    },
    {
      type: 'category',
      label: 'Manufacturers',
      collapsed: true,
      ...extractCategoryWithIntro(require('./docs/api/manufacturers/sidebar.ts').default),
    },
    {
      type: 'category',
      label: 'Model Issues',
      collapsed: true,
      ...extractCategoryWithIntro(require('./docs/api/model-issues/sidebar.ts').default),
    },
    {
      type: 'category',
      label: 'Models',
      collapsed: true,
      ...extractCategoryWithIntro(require('./docs/api/models/sidebar.ts').default),
    },
    {
      type: 'category',
      label: 'Organizations',
      collapsed: true,
      ...extractCategoryWithIntro(require('./docs/api/organizations/sidebar.ts').default),
    },
    {
      type: 'category',
      label: 'Parts',
      collapsed: true,
      ...extractCategoryWithIntro(require('./docs/api/parts/sidebar.ts').default),
    },
    {
      type: 'category',
      label: 'Search',
      collapsed: true,
      ...extractCategoryWithIntro(require('./docs/api/search/sidebar.ts').default),
    },
    {
      type: 'category',
      label: 'Sites',
      collapsed: true,
      ...extractCategoryWithIntro(require('./docs/api/sites/sidebar.ts').default),
    },
    {
      type: 'category',
      label: 'SLAs',
      collapsed: true,
      ...extractCategoryWithIntro(require('./docs/api/slas/sidebar.ts').default),
    },
    {
      type: 'category',
      label: 'Suppliers',
      collapsed: true,
      ...extractCategoryWithIntro(require('./docs/api/suppliers/sidebar.ts').default),
    },
    {
      type: 'category',
      label: 'Surveys',
      collapsed: true,
      ...extractCategoryWithIntro(require('./docs/api/surveys/sidebar.ts').default),
    },
    {
      type: 'category',
      label: 'Tags',
      collapsed: true,
      ...extractCategoryWithIntro(require('./docs/api/tags/sidebar.ts').default),
    },
    {
      type: 'category',
      label: 'Teams',
      collapsed: true,
      ...extractCategoryWithIntro(require('./docs/api/teams/sidebar.ts').default),
    },
    {
      type: 'category',
      label: 'Tickets',
      collapsed: true,
      ...extractCategoryWithIntro(require('./docs/api/tickets/sidebar.ts').default),
    },
    {
      type: 'category',
      label: 'Users',
      collapsed: true,
      ...extractCategoryWithIntro(require('./docs/api/users/sidebar.ts').default),
    },
    {
      type: 'category',
      label: 'Views',
      collapsed: true,
      ...extractCategoryWithIntro(require('./docs/api/views/sidebar.ts').default),
    },
    {
      type: 'category',
      label: 'Workflows',
      collapsed: true,
      ...extractCategoryWithIntro(require('./docs/api/workflows/sidebar.ts').default),
    },
  ],
};

export default sidebars;
