import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "api/filters/filters-api",
    },
    {
      type: "category",
      label: "Listing",
      link: {
        type: "doc",
        id: "api/filters/filters-listing",
      },
      items: [
        {
          type: "doc",
          id: "api/filters/list-filters-for-entity-type",
          label: "List filters for entity type",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/filters/list-filters",
          label: "Get Filters",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/filters/get-filter-sets-by-type",
          label: "Get filter sets by type",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Details",
      link: {
        type: "doc",
        id: "api/filters/filters-details",
      },
      items: [
        {
          type: "doc",
          id: "api/filters/get-filter-set",
          label: "Get filter set",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/filters/get-filter-set-values",
          label: "Get Filter Set Values",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/filters/get-filter-value-label",
          label: "Get the label for a filter value",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/filters/get-filter-by-key-and-product-id",
          label: "Get a filter by key and product ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/filters/get-filter-sets-by-ids",
          label: "Get filter sets by IDs",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/filters/get-custom-field-filter-sets-by-ids",
          label: "Get custom field filter sets by IDs",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Managing",
      link: {
        type: "doc",
        id: "api/filters/filters-managing",
      },
      items: [
        {
          type: "doc",
          id: "api/filters/create-filter-by-id",
          label: "Get Filter Value Labels",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/filters/create-filter",
          label: "Create a new filter",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/filters/update-filter",
          label: "Update an existing filter",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/filters/delete-filter",
          label: "Delete a filter",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/filters/delete-filter-by-origin-id",
          label: "Delete a filter by origin ID",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/filters/get-custom-field-filter-value-labels",
          label: "Get labels for custom field filter values",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/filters/save-filter-values-for-kb-articles",
          label: "Save filter values for knowledge base articles",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/filters/save-filter-values-for-views",
          label: "Save filter values for views",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/filters/get-bulk-filter-values-for-views",
          label: "Get filter values for views in bulk",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/filters/create-filter-set",
          label: "Create a new filter set",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/filters/delete-filter-set-value",
          label: "Delete a filter set value",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Schemas",
      items: [
        {
          type: "doc",
          id: "api/filters/schemas/actionresponse",
          label: "ActionResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/filters/schemas/assetsearchfacetkey",
          label: "AssetSearchFacetKey",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/filters/schemas/assetsearchfilter",
          label: "AssetSearchFilter",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/filters/schemas/assetsearchrequest",
          label: "AssetSearchRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/filters/schemas/bulkentityidrequest",
          label: "BulkEntityIdRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/filters/schemas/customfieldfilter",
          label: "CustomFieldFilter",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/filters/schemas/customfieldfilterset",
          label: "CustomFieldFilterSet",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/filters/schemas/customfieldfiltersetlistresponse",
          label: "CustomFieldFilterSetListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/filters/schemas/entityfiltervalue",
          label: "EntityFilterValue",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/filters/schemas/filtercategory",
          label: "FilterCategory",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/filters/schemas/filterdefinition",
          label: "FilterDefinition",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/filters/schemas/filterdefinitionlistresponse",
          label: "FilterDefinitionListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/filters/schemas/filtermatch",
          label: "FilterMatch",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/filters/schemas/filterset",
          label: "FilterSet",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/filters/schemas/filtersetcreateresponse",
          label: "FilterSetCreateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/filters/schemas/filtersetlistresponse",
          label: "FilterSetListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/filters/schemas/filtersettypes",
          label: "FilterSetTypes",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/filters/schemas/filtersetvalue",
          label: "FilterSetValue",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/filters/schemas/filtertype",
          label: "FilterType",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/filters/schemas/filtervalue",
          label: "FilterValue",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/filters/schemas/filtervaluesaverequest",
          label: "FilterValueSaveRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/filters/schemas/forbiddenerror",
          label: "ForbiddenError",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/filters/schemas/genericobject",
          label: "GenericObject",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/filters/schemas/getticketsrequest",
          label: "GetTicketsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/filters/schemas/getusersrequestv-1",
          label: "GetUsersRequestV1",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/filters/schemas/internalservererror",
          label: "InternalServerError",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/filters/schemas/itemcreateresponse",
          label: "ItemCreateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/filters/schemas/itemdeleteresponse",
          label: "ItemDeleteResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/filters/schemas/itemgetresponse",
          label: "ItemGetResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/filters/schemas/itemupdateresponse",
          label: "ItemUpdateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/filters/schemas/listgetresponse",
          label: "ListGetResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/filters/schemas/notfounderror",
          label: "NotFoundError",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/filters/schemas/pagingmetadata",
          label: "PagingMetadata",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/filters/schemas/ratelimiterror",
          label: "RateLimitError",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/filters/schemas/responseenvelope",
          label: "ResponseEnvelope",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/filters/schemas/responselog",
          label: "ResponseLog",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/filters/schemas/scopes",
          label: "Scopes",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/filters/schemas/softvalidationerror",
          label: "SoftValidationError",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/filters/schemas/ticketsearchfacetkey",
          label: "TicketSearchFacetKey",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/filters/schemas/ticketsearchfilter",
          label: "TicketSearchFilter",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/filters/schemas/ticketsearchrequest",
          label: "TicketSearchRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/filters/schemas/unauthorizederror",
          label: "UnauthorizedError",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/filters/schemas/validationerror",
          label: "ValidationError",
          className: "schema",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
