import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "api/users/users-api",
    },
    {
      type: "category",
      label: "Managing",
      link: {
        type: "doc",
        id: "api/users/users-managing",
      },
      items: [
        {
          type: "doc",
          id: "api/users/create-user-view",
          label: "Create user view",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/users/update-user-view-sort",
          label: "Update user view sort",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/users/delete-user-v-2",
          label: "Delete user",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/users/delete-users-by-ids-v-2",
          label: "Delete users by ID list",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/users/delete-users-by-query-v-2",
          label: "Delete users by query filter",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Searching",
      link: {
        type: "doc",
        id: "api/users/users-searching",
      },
      items: [
        {
          type: "doc",
          id: "api/users/search-users-legacy-get",
          label: "Search users (legacy GET)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/users/search-users",
          label: "Search users",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/users/count-users",
          label: "Count users matching filters",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/users/get-all-users",
          label: "Search all users including deleted",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/users/search-users-via-module",
          label: "Search users via modular service",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/users/list-users-simple",
          label: "List users (simplified records)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/users/list-user-views",
          label: "Get User Custom Views",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/users/search-users-by-keyword",
          label: "Search users by keyword",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/users/get-user-by-username",
          label: "Get user by username",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/users/get-user-by-email",
          label: "Get user by email address",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/users/search-agents-legacy-get",
          label: "Search support agents (legacy GET)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/users/search-agents",
          label: "Search support agents",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/users/list-agents-legacy-get",
          label: "List support agents (legacy GET)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/users/list-agents",
          label: "List support agents (simplified)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/users/get-users-for-view",
          label: "Get users matching a saved view",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/users/get-users-with-location-permission",
          label: "Get users with location permission",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/users/get-users-for-requestor-swap",
          label: "Search users for requestor swap",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/users/get-user-ids-for-filter-sets",
          label: "Get user IDs matching filter sets",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/users/get-users-for-my-classes",
          label: "Get users for my classes",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/users/get-user-at-associated-site",
          label: "Get user at associated site",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/users/get-user-by-external-email",
          label: "Get user by external email",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Profiles",
      link: {
        type: "doc",
        id: "api/users/users-profiles",
      },
      items: [
        {
          type: "doc",
          id: "api/users/get-user-by-id",
          label: "Retrieve user by identifier",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/users/get-user-options",
          label: "Get user options/preferences",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/users/get-user-rooms",
          label: "Get user's assigned rooms",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/users/get-simple-user",
          label: "Get simplified user record",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/users/get-site-system-user-id",
          label: "Get system user ID for a site",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/users/get-my-options",
          label: "Get current user's options/preferences",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/users/set-my-options",
          label: "Update current user's options/preferences",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/users/get-user-activities",
          label: "Get user activity timeline",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/users/get-user-relationships",
          label: "Get user relationships (guardians/students)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/users/get-user-shortcuts",
          label: "Get user's shortcuts",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/users/get-my-shortcuts",
          label: "Get current user's shortcuts",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/users/get-available-shortcuts",
          label: "Get available shortcuts",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/users/get-user-achievements",
          label: "Get user achievements",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/users/get-my-students-with-tickets",
          label: "Get students I've submitted tickets for",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Profile Updates",
      link: {
        type: "doc",
        id: "api/users/users-profile-updates",
      },
      items: [
        {
          type: "doc",
          id: "api/users/set-user-options",
          label: "Update user options/preferences",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/users/set-user-rooms",
          label: "Set user's room assignments",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/users/add-room-to-user",
          label: "Add room to user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/users/remove-room-from-user",
          label: "Remove room from user",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/users/update-user-authentication-source",
          label: "Update user authentication source",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/users/create-shortcut",
          label: "Create a new shortcut",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/users/update-shortcut",
          label: "Update a shortcut",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/users/delete-shortcut",
          label: "Delete a shortcut",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/users/award-achievement",
          label: "Award achievement to user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/users/set-user-initial-product",
          label: "Set user's initial product",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/users/bulk-set-user-rooms",
          label: "Bulk set room assignments for users",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/users/get-user-rooms-bulk",
          label: "Get room assignments for users",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Accounts",
      link: {
        type: "doc",
        id: "api/users/users-accounts",
      },
      items: [
        {
          type: "doc",
          id: "api/users/create-local-user",
          label: "Create a new local user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/users/update-user",
          label: "Update user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/users/delete-user",
          label: "Delete user",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/users/set-user-role",
          label: "Set user role",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/users/undelete-user",
          label: "Restore a deleted user",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/users/change-user-password",
          label: "Change user password",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/users/reset-user-password",
          label: "Reset user password",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/users/send-welcome-package",
          label: "Send welcome package to user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/users/send-welcome-packages-to-enabled-roles",
          label: "Send welcome packages to all enabled roles",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Account Management",
      link: {
        type: "doc",
        id: "api/users/users-account-management",
      },
      items: [
        {
          type: "doc",
          id: "api/users/migrate-user",
          label: "Migrate user data to other users",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/users/create-temp-user",
          label: "Create temporary user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/users/create-shell-user",
          label: "Create shell user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/users/convert-user-to-local",
          label: "Convert user to local account",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/users/create-local-user-from-sis",
          label: "Create local user from SIS user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/users/register-external-user",
          label: "Register external user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/users/complete-external-user-registration",
          label: "Complete external user registration",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/users/restore-iiq-admin-accounts",
          label: "Restore Incident IQ admin accounts",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Presence",
      link: {
        type: "doc",
        id: "api/users/users-presence",
      },
      items: [
        {
          type: "doc",
          id: "api/users/update-all-users-out-of-office-status",
          label: "Update all users out-of-office status",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/users/send-user-heartbeat",
          label: "Send user heartbeat",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/users/set-user-active",
          label: "Set current user as active",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/users/set-user-away",
          label: "Set current user as away",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Authentication",
      link: {
        type: "doc",
        id: "api/users/users-authentication",
      },
      items: [
        {
          type: "doc",
          id: "api/users/get-auth-token-by-user-id",
          label: "Get authentication token by user ID",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/users/get-auth-token-by-username",
          label: "Get authentication token by username",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/users/get-auth-token-for-user-with-role",
          label: "Get authentication token with role",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Utilities",
      link: {
        type: "doc",
        id: "api/users/users-utilities",
      },
      items: [
        {
          type: "doc",
          id: "api/users/get-intercom-jwt",
          label: "Generate Intercom JWT token and boot data",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/users/get-shortcut",
          label: "Get shortcut by ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/users/get-users-per-location",
          label: "Get location statistics",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/users/get-users-per-grade",
          label: "Get user count by grade level",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Bulk",
      link: {
        type: "doc",
        id: "api/users/users-bulk",
      },
      items: [
        {
          type: "doc",
          id: "api/users/bulk-set-user-custom-fields",
          label: "Bulk set user custom fields",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/users/bulk-set-user-location",
          label: "Bulk set user location",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/users/bulk-set-user-team",
          label: "Bulk set team for multiple users",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/users/bulk-unset-user-team",
          label: "Bulk remove team from multiple users",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/users/bulk-set-user-view",
          label: "Bulk set view for multiple users",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/users/bulk-set-user-initial-product",
          label: "Bulk set initial product for users",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/users/bulk-set-user-info",
          label: "Bulk set user info for multiple users",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/users/bulk-update-authentication-source",
          label: "Bulk update authentication source",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Schemas",
      items: [
        {
          type: "doc",
          id: "api/users/schemas/achievement",
          label: "Achievement",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/achievementslistgetresponse",
          label: "AchievementsListGetResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/actionresponse",
          label: "ActionResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/activity",
          label: "Activity",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/address",
          label: "Address",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/alreadyexistserror",
          label: "AlreadyExistsError",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/asset",
          label: "Asset",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/assetcategorysummary",
          label: "AssetCategorySummary",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/assetcustomfieldvalue",
          label: "AssetCustomFieldValue",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/assetdatamappinglookup",
          label: "AssetDataMappingLookup",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/assetdatamappingsource",
          label: "AssetDataMappingSource",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/assetdatamappings",
          label: "AssetDataMappings",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/assetmanufacturersummary",
          label: "AssetManufacturerSummary",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/assetmodelsummary",
          label: "AssetModelSummary",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/assetownersummary",
          label: "AssetOwnerSummary",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/assetstatussummary",
          label: "AssetStatusSummary",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/assettotalcost",
          label: "AssetTotalCost",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/assetvaluation",
          label: "AssetValuation",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/assetvaluationperiod",
          label: "AssetValuationPeriod",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/authorizeduser",
          label: "AuthorizedUser",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/authorizedusergetresponse",
          label: "AuthorizedUserGetResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/bulkjobidgetresponse",
          label: "BulkJobIdGetResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/bulksetuserinforequest",
          label: "BulkSetUserInfoRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/bulksetuserinitialproductrequest",
          label: "BulkSetUserInitialProductRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/bulksetuserlocationrequest",
          label: "BulkSetUserLocationRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/bulksetuserroomsusersroomssetrequest",
          label: "BulkSetUserRoomsUsersRoomsSetRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/bulksetuserteamrequest",
          label: "BulkSetUserTeamRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/bulksetuserviewrequest",
          label: "BulkSetUserViewRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/bulkupdateauthenticationsourcerequest",
          label: "BulkUpdateAuthenticationSourceRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/bulkusersetcustomfieldsrequest",
          label: "BulkUserSetCustomFieldsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/completeexternaluserregistrationrequest",
          label: "CompleteExternalUserRegistrationRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/complexeditorvalues",
          label: "ComplexEditorValues",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/convertusertolocalusersconverttolocalbyuseridrequest",
          label: "ConvertUserToLocalUsersConvertToLocalByUserIdRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/customfieldeditortypeid",
          label: "CustomFieldEditorTypeId",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/datafilter",
          label: "DataFilter",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/datafilteroperations",
          label: "DataFilterOperations",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/department",
          label: "Department",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/employmentstatus",
          label: "EmploymentStatus",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/errorresponse",
          label: "ErrorResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/file",
          label: "File",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/filetype",
          label: "FileType",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/filtermatch",
          label: "FilterMatch",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/forbiddenerror",
          label: "ForbiddenError",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/getauthtokenbyusernameuserstokenbysiteidbyusernamerequest",
          label: "GetAuthTokenByUsernameUsersTokenBySiteIdByUsernameRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/getidsforfiltersetrequest",
          label: "GetIdsForFilterSetRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/getuserbyemailrequest",
          label: "GetUserByEmailRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/getusersforviewusersviewbyviewidrequest",
          label: "GetUsersForViewUsersViewByViewIdRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/getusersrequestv-1",
          label: "GetUsersRequestV1",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/gradestat",
          label: "GradeStat",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/gradestatslistgetresponse",
          label: "GradeStatsListGetResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/guidcreateresponse",
          label: "GuidCreateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/guidgetresponse",
          label: "GuidGetResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/guidlistgetresponse",
          label: "GuidListGetResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/idsforfiltersetslistgetresponse",
          label: "IdsForFilterSetsListGetResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/idsforfiltersetsresponse",
          label: "IdsForFilterSetsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/intercombootdata",
          label: "IntercomBootData",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/intercombootdatagetresponse",
          label: "IntercomBootDataGetResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/intercomcompanyattributes",
          label: "IntercomCompanyAttributes",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/intercomuserattributes",
          label: "IntercomUserAttributes",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/internalservererror",
          label: "InternalServerError",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/itemcreateresponse",
          label: "ItemCreateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/itemdeleteresponse",
          label: "ItemDeleteResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/itemgetresponse",
          label: "ItemGetResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/itemupdateresponse",
          label: "ItemUpdateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/listdeleteresponse",
          label: "ListDeleteResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/listgetresponse",
          label: "ListGetResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/location",
          label: "Location",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/locationcustomfieldvalue",
          label: "LocationCustomFieldValue",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/locationroom",
          label: "LocationRoom",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/locationroomavailabletime",
          label: "LocationRoomAvailableTime",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/locationroomcustomfieldvalue",
          label: "LocationRoomCustomFieldValue",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/locationroomslistgetresponse",
          label: "LocationRoomsListGetResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/locationstat",
          label: "LocationStat",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/locationstatslistgetresponse",
          label: "LocationStatsListGetResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/locationstatustype",
          label: "LocationStatusType",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/locationtype",
          label: "LocationType",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/migrateuserrequest",
          label: "MigrateUserRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/newlocaluserrequest",
          label: "NewLocalUserRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/notfounderror",
          label: "NotFoundError",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/pagingmetadata",
          label: "PagingMetadata",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/pagingoptions",
          label: "PagingOptions",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/ratelimiterror",
          label: "RateLimitError",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/registerexternaluserrequest",
          label: "RegisterExternalUserRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/registerexternaluserresponse",
          label: "RegisterExternalUserResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/requestoptions",
          label: "RequestOptions",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/responseenvelope",
          label: "ResponseEnvelope",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/responselog",
          label: "ResponseLog",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/restoreiiqadminaccountsrequest",
          label: "RestoreIIQAdminAccountsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/role",
          label: "Role",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/setuserawayrequest",
          label: "SetUserAwayRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/setusercustomfieldsrequest",
          label: "SetUserCustomFieldsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/setuserinforequest",
          label: "SetUserInfoRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/setuserinitialproductrequest",
          label: "SetUserInitialProductRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/setuserlocationrequest",
          label: "SetUserLocationRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/setuserlocationrequestroom",
          label: "SetUserLocationRequestRoom",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/setuserpasswordrequest",
          label: "SetUserPasswordRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/setuserrolerequest",
          label: "SetUserRoleRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/setuserteamrequest",
          label: "SetUserTeamRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/shortcut",
          label: "Shortcut",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/shortcutcreateresponse",
          label: "ShortcutCreateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/shortcutgetresponse",
          label: "ShortcutGetResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/shortcutupdateresponse",
          label: "ShortcutUpdateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/shortcutslistgetresponse",
          label: "ShortcutsListGetResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/simpleuser",
          label: "SimpleUser",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/simpleusercreateresponse",
          label: "SimpleUserCreateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/simpleusergetresponse",
          label: "SimpleUserGetResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/simpleuserslistgetresponse",
          label: "SimpleUsersListGetResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/site",
          label: "Site",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/softvalidationerror",
          label: "SoftValidationError",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/sortoptions",
          label: "SortOptions",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/source",
          label: "Source",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/stringkeyvaluepair",
          label: "StringKeyValuePair",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/tickettemplaterecurringschedule",
          label: "TicketTemplateRecurringSchedule",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/unauthorizederror",
          label: "UnauthorizedError",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/updateuserauthenticationsourcerequest",
          label: "UpdateUserAuthenticationSourceRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/user",
          label: "User",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/useractivitieslistgetresponse",
          label: "UserActivitiesListGetResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/usercustomfieldvalue",
          label: "UserCustomFieldValue",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/userdatamappinglookup",
          label: "UserDataMappingLookup",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/userdatamappingsource",
          label: "UserDataMappingSource",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/userdatamappings",
          label: "UserDataMappings",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/userdetail",
          label: "UserDetail",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/userdetailcreateresponse",
          label: "UserDetailCreateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/userdetailgetresponse",
          label: "UserDetailGetResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/userdetailupdateresponse",
          label: "UserDetailUpdateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/usernotificationsettings",
          label: "UserNotificationSettings",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/useroptions",
          label: "UserOptions",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/useroptionsgetresponse",
          label: "UserOptionsGetResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/useroptionslocations",
          label: "UserOptionsLocations",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/useroutofofficeupdateallresponse",
          label: "UserOutOfOfficeUpdateAllResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/useroutofofficeupdateresponse",
          label: "UserOutOfOfficeUpdateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/userrelationship",
          label: "UserRelationship",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/userrelationshipslistgetresponse",
          label: "UserRelationshipsListGetResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/userroom",
          label: "UserRoom",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/userroomslistgetresponse",
          label: "UserRoomsListGetResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/usersearchfacetkey",
          label: "UserSearchFacetKey",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/usersearchfilter",
          label: "UserSearchFilter",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/usersearchrequest",
          label: "UserSearchRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/usersearchresponse",
          label: "UserSearchResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/userupdaterequest",
          label: "UserUpdateRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/userview",
          label: "UserView",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/userviewslistresponse",
          label: "UserViewsListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/userwithlocationpermission",
          label: "UserWithLocationPermission",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/userslistgetresponse",
          label: "UsersListGetResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/userswithlocationpermissionlistgetresponse",
          label: "UsersWithLocationPermissionListGetResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/uuidlist",
          label: "UuidList",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/validationerror",
          label: "ValidationError",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/view",
          label: "View",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/viewcolumn",
          label: "ViewColumn",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/viewcolumnoption",
          label: "ViewColumnOption",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/viewdefinition",
          label: "ViewDefinition",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/viewfiltervalue",
          label: "ViewFilterValue",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/viewitemcreateresponse",
          label: "ViewItemCreateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/viewschedule",
          label: "ViewSchedule",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/viewsharesummary",
          label: "ViewShareSummary",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/viewsort",
          label: "ViewSort",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/users/schemas/viewtab",
          label: "ViewTab",
          className: "schema",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
