import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "api/audits/audits-api",
    },
    {
      type: "category",
      label: "Policies",
      link: {
        type: "doc",
        id: "api/audits/audits-policies",
      },
      items: [
        {
          type: "doc",
          id: "api/audits/get-asset-audit-policies",
          label: "List asset audit policies",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/audits/get-asset-audit-policy",
          label: "Get audit policy details",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/audits/add-asset-to-audit-policy",
          label: "Add asset to audit policy",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/audits/get-asset-audit-policy-assets",
          label: "List assets covered by audit policy",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Schedules",
      link: {
        type: "doc",
        id: "api/audits/audits-schedules",
      },
      items: [
        {
          type: "doc",
          id: "api/audits/get-asset-audit-policy-schedule",
          label: "Get audit policy schedule details",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/audits/get-asset-audit-policy-schedules-for-asset",
          label: "List audit schedules for an asset",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/audits/get-asset-audit-policy-schedule-assets",
          label: "List assets in audit schedule instance",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Schemas",
      items: [
        {
          type: "doc",
          id: "api/audits/schemas/actionresponse",
          label: "ActionResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/audits/schemas/address",
          label: "Address",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/audits/schemas/app",
          label: "App",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/audits/schemas/asset",
          label: "Asset",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/audits/schemas/assetauditpolicy",
          label: "AssetAuditPolicy",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/audits/schemas/assetauditpolicyschedule",
          label: "AssetAuditPolicySchedule",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/audits/schemas/assetcategorysummary",
          label: "AssetCategorySummary",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/audits/schemas/assetcustomfieldvalue",
          label: "AssetCustomFieldValue",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/audits/schemas/assetdatamappinglookup",
          label: "AssetDataMappingLookup",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/audits/schemas/assetdatamappingsource",
          label: "AssetDataMappingSource",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/audits/schemas/assetdatamappings",
          label: "AssetDataMappings",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/audits/schemas/assetfundingtype",
          label: "AssetFundingType",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/audits/schemas/assetinventorytype",
          label: "AssetInventoryType",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/audits/schemas/assetmanufacturersummary",
          label: "AssetManufacturerSummary",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/audits/schemas/assetmodelsummary",
          label: "AssetModelSummary",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/audits/schemas/assetownersummary",
          label: "AssetOwnerSummary",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/audits/schemas/assetstatussummary",
          label: "AssetStatusSummary",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/audits/schemas/assetstatustype",
          label: "AssetStatusType",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/audits/schemas/assettotalcost",
          label: "AssetTotalCost",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/audits/schemas/assettype",
          label: "AssetType",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/audits/schemas/assetvaluation",
          label: "AssetValuation",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/audits/schemas/assetvaluationperiod",
          label: "AssetValuationPeriod",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/audits/schemas/closereasontype",
          label: "CloseReasonType",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/audits/schemas/complexeditorvalues",
          label: "ComplexEditorValues",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/audits/schemas/customfieldeditortypeid",
          label: "CustomFieldEditorTypeId",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/audits/schemas/itemgetresponse",
          label: "ItemGetResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/audits/schemas/itemgetresponse-assetauditpolicy",
          label: "ItemGetResponse_AssetAuditPolicy",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/audits/schemas/itemgetresponse-assetauditpolicyschedule",
          label: "ItemGetResponse_AssetAuditPolicySchedule",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/audits/schemas/listgetresponse",
          label: "ListGetResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/audits/schemas/listgetresponse-asset",
          label: "ListGetResponse_Asset",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/audits/schemas/listgetresponse-assetauditpolicy",
          label: "ListGetResponse_AssetAuditPolicy",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/audits/schemas/listgetresponse-assetauditpolicyschedule",
          label: "ListGetResponse_AssetAuditPolicySchedule",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/audits/schemas/location",
          label: "Location",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/audits/schemas/locationcustomfieldvalue",
          label: "LocationCustomFieldValue",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/audits/schemas/locationroom",
          label: "LocationRoom",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/audits/schemas/locationroomavailabletime",
          label: "LocationRoomAvailableTime",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/audits/schemas/locationroomcustomfieldvalue",
          label: "LocationRoomCustomFieldValue",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/audits/schemas/locationroomtype",
          label: "LocationRoomType",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/audits/schemas/locationstatustype",
          label: "LocationStatusType",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/audits/schemas/locationtype",
          label: "LocationType",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/audits/schemas/pagingmetadata",
          label: "PagingMetadata",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/audits/schemas/producttier",
          label: "ProductTier",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/audits/schemas/purchaseorderstatustype",
          label: "PurchaseOrderStatusType",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/audits/schemas/role",
          label: "Role",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/audits/schemas/site",
          label: "Site",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/audits/schemas/siteapphook",
          label: "SiteAppHook",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/audits/schemas/siteappsconfiguration",
          label: "SiteAppsConfiguration",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/audits/schemas/siteconfigurationsetting",
          label: "SiteConfigurationSetting",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/audits/schemas/sitekpi",
          label: "SiteKpi",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/audits/schemas/sitesettings",
          label: "SiteSettings",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/audits/schemas/sitestatus",
          label: "SiteStatus",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/audits/schemas/sitestatustype",
          label: "SiteStatusType",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/audits/schemas/softvalidationerror",
          label: "SoftValidationError",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/audits/schemas/source",
          label: "Source",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/audits/schemas/tag",
          label: "Tag",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/audits/schemas/ticketprioritylevel",
          label: "TicketPriorityLevel",
          className: "schema",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
