import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "api/events/events-api",
    },
    {
      type: "category",
      label: "Creating",
      link: {
        type: "doc",
        id: "api/events/events-creating",
      },
      items: [
        {
          type: "doc",
          id: "api/events/create-event",
          label: "Create event",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/events/create-events",
          label: "Create multiple events",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Deleting",
      link: {
        type: "doc",
        id: "api/events/events-deleting",
      },
      items: [
        {
          type: "doc",
          id: "api/events/delete-events-by-ids",
          label: "Delete events by IDs",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/events/delete-event",
          label: "Delete event by ID",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/events/delete-recurring-event",
          label: "Delete recurring event instance",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/events/delete-events-by-query",
          label: "Delete events by query",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/events/bulk-delete-events",
          label: "Bulk delete events",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Details",
      link: {
        type: "doc",
        id: "api/events/events-details",
      },
      items: [
        {
          type: "doc",
          id: "api/events/get-event",
          label: "Get event by ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/events/get-events-by-ids",
          label: "Get events by IDs",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/events/get-event-attachments",
          label: "Get event attachments",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/events/get-event-fee-package",
          label: "Get event fee package",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Querying",
      link: {
        type: "doc",
        id: "api/events/events-querying",
      },
      items: [
        {
          type: "doc",
          id: "api/events/get-events-by-query-get",
          label: "Query events (GET)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/events/get-events-by-query-post",
          label: "Query events (POST)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/events/get-user-events-get",
          label: "Get user events (GET)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/events/get-user-events-post",
          label: "Get user events (POST)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/events/get-events-by-query-with-deleted-get",
          label: "Query events including deleted (GET)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/events/get-events-by-query-with-deleted-post",
          label: "Query events including deleted (POST)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/events/get-available-rooms",
          label: "Get available rooms",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/events/get-available-times",
          label: "Get available times",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Updating",
      link: {
        type: "doc",
        id: "api/events/events-updating",
      },
      items: [
        {
          type: "doc",
          id: "api/events/save-event-attachments",
          label: "Save event attachments",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/events/update-event",
          label: "Update event by ID",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/events/update-events-by-query",
          label: "Update events by query",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/events/update-events-by-ids",
          label: "Update events by IDs",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/events/calculate-event-fees",
          label: "Calculate event fees",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/events/process-queued-events",
          label: "Process queued events",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/events/bulk-calculate-event-fees",
          label: "Bulk calculate event fees",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/events/bulk-set-event-info",
          label: "Bulk set event info",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Recurrence",
      link: {
        type: "doc",
        id: "api/events/events-recurrence",
      },
      items: [
        {
          type: "doc",
          id: "api/events/create-event-series",
          label: "Create event series",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/events/add-event-series-dates",
          label: "Add dates to event series",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/events/project-events",
          label: "Project event occurrences",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/events/get-event-recurrence",
          label: "Get active events in series",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Rsvp",
      link: {
        type: "doc",
        id: "api/events/events-rsvp",
      },
      items: [
        {
          type: "doc",
          id: "api/events/validate-schedule",
          label: "Validate schedule",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/events/validate-schedules-all",
          label: "Validate all schedules",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/events/validate-schedules-calendar-conflicts",
          label: "Validate calendar conflicts",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/events/validate-schedules-place-reservations",
          label: "Validate place reservations",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/events/validate-schedules-conflicting-events",
          label: "Validate conflicting events",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Types",
      link: {
        type: "doc",
        id: "api/events/events-types",
      },
      items: [
        {
          type: "doc",
          id: "api/events/get-event-type",
          label: "Get event type by ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/events/delete-event-type",
          label: "Delete event type by ID",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/events/update-event-type",
          label: "Update event type by ID",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/events/get-event-types-by-query-get",
          label: "Query event types (GET)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/events/get-event-types-by-query-post",
          label: "Query event types (POST)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/events/delete-event-types-by-query",
          label: "Delete event types by query",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/events/update-event-types-by-query",
          label: "Update event types by query",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/events/get-event-types-by-ids",
          label: "Get event types by IDs",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/events/create-event-types",
          label: "Create multiple event types",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/events/delete-event-types-by-ids",
          label: "Delete event types by IDs",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/events/update-event-types-by-ids",
          label: "Update event types by IDs",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/events/create-event-type",
          label: "Create event type",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Schemas",
      items: [
        {
          type: "doc",
          id: "api/events/schemas/actionresponse",
          label: "ActionResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/events/schemas/addeventseriesdatesrequest",
          label: "AddEventSeriesDatesRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/events/schemas/address",
          label: "Address",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/events/schemas/bulkdataoperationitemresponse",
          label: "BulkDataOperationItemResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/events/schemas/bulkjobeventrequest",
          label: "BulkJobEventRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/events/schemas/complexeditorvalues",
          label: "ComplexEditorValues",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/events/schemas/createeventseriesrequest",
          label: "CreateEventSeriesRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/events/schemas/datafilter",
          label: "DataFilter",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/events/schemas/datafilteroperations",
          label: "DataFilterOperations",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/events/schemas/entityfiledetail",
          label: "EntityFileDetail",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/events/schemas/entityfiledetaillistresponse",
          label: "EntityFileDetailListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/events/schemas/errorresponse",
          label: "ErrorResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/events/schemas/event",
          label: "Event",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/events/schemas/eventbatchcreateresponse",
          label: "EventBatchCreateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/events/schemas/eventbatchupdateresponse",
          label: "EventBatchUpdateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/events/schemas/eventitemresponse",
          label: "EventItemResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/events/schemas/eventlistresponse",
          label: "EventListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/events/schemas/eventschedule",
          label: "EventSchedule",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/events/schemas/eventseriesdata",
          label: "EventSeriesData",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/events/schemas/eventstatustype",
          label: "EventStatusType",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/events/schemas/eventtype",
          label: "EventType",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/events/schemas/eventtypebatchcreateresponse",
          label: "EventTypeBatchCreateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/events/schemas/eventtypebatchupdateresponse",
          label: "EventTypeBatchUpdateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/events/schemas/eventtypeitemresponse",
          label: "EventTypeItemResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/events/schemas/eventtypelistresponse",
          label: "EventTypeListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/events/schemas/eventupdatevalidationlistresponse",
          label: "EventUpdateValidationListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/events/schemas/eventupdatevalidationresponse",
          label: "EventUpdateValidationResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/events/schemas/eventsdeleteresponse",
          label: "EventsDeleteResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/events/schemas/eventsupdateresponse",
          label: "EventsUpdateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/events/schemas/feeschedulepackage",
          label: "FeeSchedulePackage",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/events/schemas/feeschedulepackageresponse",
          label: "FeeSchedulePackageResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/events/schemas/geteventsrequest",
          label: "GetEventsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/events/schemas/guiditemresponse",
          label: "GuidItemResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/events/schemas/guidlistresponse",
          label: "GuidListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/events/schemas/location",
          label: "Location",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/events/schemas/locationcustomfieldvalue",
          label: "LocationCustomFieldValue",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/events/schemas/locationroom",
          label: "LocationRoom",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/events/schemas/locationroomavailabletime",
          label: "LocationRoomAvailableTime",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/events/schemas/locationroomcustomfieldvalue",
          label: "LocationRoomCustomFieldValue",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/events/schemas/locationstatustype",
          label: "LocationStatusType",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/events/schemas/locationtype",
          label: "LocationType",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/events/schemas/organization",
          label: "Organization",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/events/schemas/organizationcustomfieldvalue",
          label: "OrganizationCustomFieldValue",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/events/schemas/organizationstatustype",
          label: "OrganizationStatusType",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/events/schemas/organizationtype",
          label: "OrganizationType",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/events/schemas/pagingmetadata",
          label: "PagingMetadata",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/events/schemas/schedulevalidationlistresponse",
          label: "ScheduleValidationListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/events/schemas/schedulevalidationrequest",
          label: "ScheduleValidationRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/events/schemas/schedulevalidationresponse",
          label: "ScheduleValidationResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/events/schemas/simpleuser",
          label: "SimpleUser",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/events/schemas/slimeventschedule",
          label: "SlimEventSchedule",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/events/schemas/softvalidationerror",
          label: "SoftValidationError",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/events/schemas/updateeventfiledetailsrequest",
          label: "UpdateEventFileDetailsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/events/schemas/updateeventrequest",
          label: "UpdateEventRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/events/schemas/updateeventrequestlistresponse",
          label: "UpdateEventRequestListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/events/schemas/updateeventtyperequest",
          label: "UpdateEventTypeRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/events/schemas/updateeventtypesrequest",
          label: "UpdateEventTypesRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/events/schemas/updateeventsrequest",
          label: "UpdateEventsRequest",
          className: "schema",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
