import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "api/tickets/tickets-api",
    },
    {
      type: "category",
      label: "Searching",
      link: {
        type: "doc",
        id: "api/tickets/tickets-searching",
      },
      items: [
        {
          type: "doc",
          id: "api/tickets/search-tickets-global",
          label: "Search tickets globally",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/get-ticket-stats-global",
          label: "Get global ticket statistics",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/list-ticket-views",
          label: "List ticket views",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/tickets/search-tickets",
          label: "Search tickets",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/get-ticket-count",
          label: "Count tickets matching criteria",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/get-ticket-view",
          label: "Get ticket view",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/tickets/list-ticket-slas",
          label: "List Ticket SLAs",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/get-ticket-ids-for-filter-sets",
          label: "Get ticket IDs for filter sets",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/get-ticket-assets-by-model",
          label: "Find ticket assets by model/category",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/get-similar-tickets",
          label: "Find similar tickets",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/list-ticket-timeline",
          label: "Get ticket timeline (POST)",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Assigning",
      link: {
        type: "doc",
        id: "api/tickets/tickets-assigning",
      },
      items: [
        {
          type: "doc",
          id: "api/tickets/assign-ticket",
          label: "Assign ticket",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/unassign-ticket-from-user",
          label: "Unassign ticket from user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/unassign-ticket-from-team",
          label: "Unassign ticket from team",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/unassign-ticket-sla",
          label: "Unassign SLA from ticket",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/assign-ticket-sla",
          label: "Assign SLA to ticket",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/unassign-ticket-from-related",
          label: "Unassign ticket from related ticket",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/set-ticket-owner-and-for",
          label: "Set ticket owner and requester",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Bulk",
      link: {
        type: "doc",
        id: "api/tickets/tickets-bulk",
      },
      items: [
        {
          type: "doc",
          id: "api/tickets/bulk-assign-tickets",
          label: "Bulk assign tickets",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/bulk-set-ticket-issue",
          label: "Bulk set issue type",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/bulk-set-ticket-priority",
          label: "Bulk set ticket priority",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/bulk-set-ticket-due-date",
          label: "Bulk set due dates",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/bulk-remove-ticket-due-date",
          label: "Bulk remove due dates",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/bulk-follow-tickets",
          label: "Bulk follow tickets",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/bulk-unfollow-tickets",
          label: "Bulk unfollow tickets",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/bulk-assign-ticket-sla",
          label: "Bulk assign SLA to tickets",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/bulk-remove-ticket-sla",
          label: "Bulk remove SLA from tickets",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/tickets/bulk-set-ticket-status",
          label: "Bulk set ticket status",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/bulk-work-tickets",
          label: "Bulk add work to tickets",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/bulk-copy-tickets",
          label: "Bulk copy tickets",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/bulk-run-ticket-rules",
          label: "Bulk run rules on tickets",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/bulk-set-ticket-view",
          label: "Bulk set ticket view",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/bulk-assign-ticket-workpackage",
          label: "Bulk assign workpackage to tickets",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/bulk-delete-tickets",
          label: "Bulk delete tickets",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/tickets/bulk-update-ticket-info",
          label: "Bulk update ticket custom fields",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Communication",
      link: {
        type: "doc",
        id: "api/tickets/tickets-communication",
      },
      items: [
        {
          type: "doc",
          id: "api/tickets/get-ticket-activities",
          label: "Get all activities for a ticket",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/tickets/create-ticket-activity",
          label: "Add activity to ticket",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/get-ticket-activity-by-id",
          label: "Get ticket activity by ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/tickets/delete-ticket-activity",
          label: "Delete ticket activity",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/tickets/send-ticket-activity-notification",
          label: "Resend activity notification",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/update-ticket-activity",
          label: "Update ticket activity",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/change-ticket-activity-visibility",
          label: "Change activity visibility",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/get-ticket-followers",
          label: "Get ticket followers",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/tickets/create-ticket-activity-batch",
          label: "Add batch of activities to ticket",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/add-ticket-follower-user",
          label: "Add user as ticket follower",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/remove-ticket-follower-user",
          label: "Remove user as ticket follower",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/tickets/add-ticket-follower-team",
          label: "Add team as ticket followers",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/remove-ticket-follower-team",
          label: "Remove team as ticket followers",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/tickets/undelete-ticket-activity",
          label: "Restore deleted ticket activity",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/tickets/get-activities-for-tickets",
          label: "Get activities for multiple tickets",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Updating",
      link: {
        type: "doc",
        id: "api/tickets/tickets-updating",
      },
      items: [
        {
          type: "doc",
          id: "api/tickets/update-ticket-view",
          label: "Update ticket view",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/delete-ticket-view",
          label: "Delete ticket view",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/tickets/update-ticket",
          label: "Update ticket",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/create-ticket-view",
          label: "Create ticket view",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/update-ticket-subject",
          label: "Update ticket subject",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/update-ticket-assets",
          label: "Update ticket assets",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/update-ticket-description",
          label: "Update ticket description",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/update-ticket-view-sort",
          label: "Update ticket view sort",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/update-ticket-custom-fields",
          label: "Update ticket custom fields",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/update-ticket-view-schedules",
          label: "Update ticket view schedules",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/update-ticket-tags",
          label: "Update ticket tags",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/update-ticket-assets-by-category",
          label: "Update ticket assets by category",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/add-ticket-tag",
          label: "Add tag to ticket",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/remove-ticket-tag",
          label: "Remove tag from ticket",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/tickets/unconfirm-ticket-issue",
          label: "Unconfirm ticket issue",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/set-ticket-priority",
          label: "Set ticket priority",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/set-ticket-due-date",
          label: "Set ticket due date",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/save-ticket-due-date-reminders",
          label: "Save due date reminders",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/change-ticket-issue",
          label: "Change ticket issue type",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/mark-ticket-urgent",
          label: "Mark ticket as urgent",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/mark-ticket-not-urgent",
          label: "Remove urgent flag from ticket",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/mark-ticket-sensitive",
          label: "Mark ticket as sensitive",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/mark-ticket-not-sensitive",
          label: "Remove sensitive flag from ticket",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Submitting",
      link: {
        type: "doc",
        id: "api/tickets/tickets-submitting",
      },
      items: [
        {
          type: "doc",
          id: "api/tickets/create-ticket",
          label: "Create ticket",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/copy-ticket",
          label: "Copy ticket",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/create-simple-ticket",
          label: "Create ticket (simplified)",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Subtasks",
      link: {
        type: "doc",
        id: "api/tickets/tickets-subtasks",
      },
      items: [
        {
          type: "doc",
          id: "api/tickets/get-subtasks-for-ticket",
          label: "Get subtasks for a ticket",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/tickets/delete-subtask",
          label: "Delete subtask",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/tickets/create-subtask",
          label: "Create subtask",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/get-user-subtasks",
          label: "Get my open subtasks",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/tickets/assign-subtask",
          label: "Assign subtask to user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/complete-subtask",
          label: "Complete subtask",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/unassign-subtask",
          label: "Unassign subtask",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/revert-subtask-completion",
          label: "Revert subtask completion",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/duplicate-subtask",
          label: "Duplicate subtask",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/convert-subtask-to-ticket",
          label: "Convert subtask to ticket",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/delete-subticket",
          label: "Delete subticket",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/tickets/get-subtask-source-ticket",
          label: "Get source ticket for a subtask",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/tickets/update-subtask-sort-order",
          label: "Update subtask sort order",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/get-user-subtask-groups",
          label: "Get subtask groups for a user",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/tickets/get-my-subtask-groups",
          label: "Get my subtask groups",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/tickets/update-subtask-group",
          label: "Update subtask group",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/delete-subtask-group",
          label: "Delete subtask group",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/tickets/create-subtask-group",
          label: "Create subtask group",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/assign-subtasks-to-group",
          label: "Assign subtasks to group",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/ungroup-subtask-group-from-ticket",
          label: "Ungroup subtasks from group",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/remove-subtask-group-from-ticket",
          label: "Remove group from ticket",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Workflow",
      link: {
        type: "doc",
        id: "api/tickets/tickets-workflow",
      },
      items: [
        {
          type: "doc",
          id: "api/tickets/delete-ticket",
          label: "Delete ticket",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/tickets/update-ticket-next-step",
          label: "Update next step",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/list-ticket-next-step-types",
          label: "List next-step types",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/tickets/set-ticket-status",
          label: "Update ticket status",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/get-ticket-next-step-type",
          label: "Get next-step type",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/tickets/search-ticket-next-steps",
          label: "Search ticket next steps",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/confirm-ticket-issue",
          label: "Confirm ticket issue",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/change-ticket-approver",
          label: "Change ticket approver",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/set-ticket-next-step-resolvable",
          label: "Set next step as user resolvable",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/start-ticket",
          label: "Start ticket work",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/has-active-events",
          label: "Check for active scheduled events",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/tickets/close-ticket",
          label: "Resolve ticket",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/delete-workflow-approval",
          label: "Delete pending workflow approval",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/tickets/cancel-ticket",
          label: "Cancel ticket",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/process-ticket-workflow-approval",
          label: "Process workflow approval",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/log-support-ticket",
          label: "Log support ticket",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/get-workflow-step-status",
          label: "Get workflow step status",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/tickets/mark-ticket-as-duplicate",
          label: "Mark ticket as duplicate",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/set-ticket-waiting-on-requestor",
          label: "Set ticket to waiting on requestor",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/set-ticket-requestor-responded",
          label: "Mark requestor has responded",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/create-ticket-next-step",
          label: "Create next step for ticket",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/undelete-ticket",
          label: "Restore deleted ticket",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/tickets/resolve-ticket-next-step",
          label: "Resolve ticket next step",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/send-ticket-for-approval",
          label: "Send ticket for approval",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/tickets/process-ticket-approval",
          label: "Respond to approval request",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Metadata",
      link: {
        type: "doc",
        id: "api/tickets/tickets-metadata",
      },
      items: [
        {
          type: "doc",
          id: "api/tickets/list-ticket-priority-levels",
          label: "List Ticket Priorities",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/tickets/list-ticket-statuses",
          label: "List all ticket statuses",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/tickets/get-ticket-status-by-id",
          label: "Get ticket status by ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/tickets/get-ticket-sources",
          label: "Get ticket sources",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/tickets/get-ticket-fields",
          label: "Get ticket field definitions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/tickets/get-all-workflow-statuses",
          label: "Get all workflow statuses",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/tickets/get-workflow-statuses",
          label: "Get statuses for specific workflow",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/tickets/get-close-reason-types",
          label: "Get close reason types",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/tickets/list-resolution-actions",
          label: "List resolution actions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/tickets/get-resolution-action",
          label: "Get resolution action",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Viewing",
      link: {
        type: "doc",
        id: "api/tickets/tickets-viewing",
      },
      items: [
        {
          type: "doc",
          id: "api/tickets/get-ticket-sla",
          label: "Get Ticket SLA",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/tickets/get-ticket-timeline",
          label: "Get ticket timeline",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/tickets/get-ticket",
          label: "Get Ticket Details",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/tickets/get-ticket-assets",
          label: "Get ticket assets",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/tickets/get-ticket-roles",
          label: "Get roles associated with ticket",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/tickets/get-ticket-location-types",
          label: "Get location types for ticket",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/tickets/get-ticket-status",
          label: "Get ticket status",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/tickets/get-ticket-asset-groups",
          label: "Get asset groups for ticket",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/tickets/get-related-tickets",
          label: "Get related tickets",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/tickets/get-ticket-kb-articles",
          label: "Get related knowledge base articles",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/tickets/get-ticket-next-steps",
          label: "Get ticket next steps",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/tickets/get-ticket-next-step",
          label: "Get next step details",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/tickets/get-ticket-users",
          label: "Get users associated with ticket",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/tickets/get-ticket-teams",
          label: "Get teams associated with ticket",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/tickets/get-ticket-locations",
          label: "Get locations associated with ticket",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/tickets/get-ticket-due-date-reminders",
          label: "Get due date reminders for ticket",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/tickets/get-ticket-approvals",
          label: "Get ticket approvals",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Schemas",
      items: [
        {
          type: "doc",
          id: "api/tickets/schemas/actionresponse",
          label: "ActionResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/address",
          label: "Address",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/appmodelissue",
          label: "AppModelIssue",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/assignticketsubtaskgrouprequest",
          label: "AssignTicketSubtaskGroupRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/bulkassignslarequest",
          label: "BulkAssignSlaRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/bulkassignticketsrequest",
          label: "BulkAssignTicketsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/bulkassignworkpackagerequest",
          label: "BulkAssignWorkpackageRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/bulkcopyticketrequest",
          label: "BulkCopyTicketRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/bulkdeleteticketsrequest",
          label: "BulkDeleteTicketsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/bulkfollowticketsrequest",
          label: "BulkFollowTicketsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/bulkoperationresponse",
          label: "BulkOperationResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/bulkremoveduedaterequest",
          label: "BulkRemoveDueDateRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/bulkremoveslarequest",
          label: "BulkRemoveSlaRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/bulkrunentityrulerequest",
          label: "BulkRunEntityRuleRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/bulkrunticketrulesrequest",
          label: "BulkRunTicketRulesRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/bulksetduedaterequest",
          label: "BulkSetDueDateRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/bulksetissuerequest",
          label: "BulkSetIssueRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/bulksetpriorityrequest",
          label: "BulkSetPriorityRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/bulksetstatusrequest",
          label: "BulkSetStatusRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/bulksetticketviewrequest",
          label: "BulkSetTicketViewRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/bulkworkticketsrequest",
          label: "BulkWorkTicketsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/closereason",
          label: "CloseReason",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/closereasontype",
          label: "CloseReasonType",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/closereasontypelistresponse",
          label: "CloseReasonTypeListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/complexeditorvalues",
          label: "ComplexEditorValues",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/createsubtaskgroupresponse",
          label: "CreateSubtaskGroupResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/customfieldvalue",
          label: "CustomFieldValue",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/duedatepackage",
          label: "DueDatePackage",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/errorresponse",
          label: "ErrorResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/file",
          label: "File",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/filetype",
          label: "FileType",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/forbiddenerror",
          label: "ForbiddenError",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/getidsforfiltersetrequest",
          label: "GetIdsForFilterSetRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/getticketassetsrequest",
          label: "GetTicketAssetsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/getticketassetsresponse",
          label: "GetTicketAssetsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/gettickettimelinerequest",
          label: "GetTicketTimelineRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/getticketsrequest",
          label: "GetTicketsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/idsforfiltersetsresponse",
          label: "IdsForFilterSetsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/issue",
          label: "Issue",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/itemcreateresponse",
          label: "ItemCreateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/itemdeleteresponse",
          label: "ItemDeleteResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/itemgetresponse",
          label: "ItemGetResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/itemupdateresponse",
          label: "ItemUpdateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/kbarticle",
          label: "KbArticle",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/listgetresponse",
          label: "ListGetResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/location",
          label: "Location",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/locationcustomfieldvalue",
          label: "LocationCustomFieldValue",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/locationlistresponse",
          label: "LocationListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/locationroom",
          label: "LocationRoom",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/locationroomavailabletime",
          label: "LocationRoomAvailableTime",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/locationroomcustomfieldvalue",
          label: "LocationRoomCustomFieldValue",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/locationstatustype",
          label: "LocationStatusType",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/locationtype",
          label: "LocationType",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/locationtypelistresponse",
          label: "LocationTypeListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/metric",
          label: "Metric",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/modelissue",
          label: "ModelIssue",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/pagingmetadata",
          label: "PagingMetadata",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/pagingoptions",
          label: "PagingOptions",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/reminder",
          label: "Reminder",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/resolutionactionlistresponse",
          label: "ResolutionActionListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/resolutionactionresponse",
          label: "ResolutionActionResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/resolutionactionsummary",
          label: "ResolutionActionSummary",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/responseenvelope",
          label: "ResponseEnvelope",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/responselog",
          label: "ResponseLog",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/role",
          label: "Role",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/rolelistresponse",
          label: "RoleListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/sendticketforapprovalrequest",
          label: "SendTicketForApprovalRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/setticketissuerequest",
          label: "SetTicketIssueRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/setticketpriorityrequest",
          label: "SetTicketPriorityRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/setticketprogressrequest",
          label: "SetTicketProgressRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/similarticketoptions",
          label: "SimilarTicketOptions",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/simpleticketcreateresponse",
          label: "SimpleTicketCreateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/simpleticketrequest",
          label: "SimpleTicketRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/site",
          label: "Site",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/sla",
          label: "Sla",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/slaassignrequest",
          label: "SlaAssignRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/softvalidationerror",
          label: "SoftValidationError",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/sortoptions",
          label: "SortOptions",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/subtask",
          label: "Subtask",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/subtaskgroup",
          label: "SubtaskGroup",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/subtaskgrouplistitem",
          label: "SubtaskGroupListItem",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/subtaskgrouplistresponse",
          label: "SubtaskGroupListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/subtasklistresponse",
          label: "SubtaskListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/subtaskresponse",
          label: "SubtaskResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/subtasksourceticketresponse",
          label: "SubtaskSourceTicketResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/tag",
          label: "Tag",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/team",
          label: "Team",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/teamlistresponse",
          label: "TeamListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticket",
          label: "Ticket",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketactivitiesresponse",
          label: "TicketActivitiesResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketactivity",
          label: "TicketActivity",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketactivityaction",
          label: "TicketActivityAction",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketactivityactionevent",
          label: "TicketActivityActionEvent",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketactivityappactivity",
          label: "TicketActivityAppActivity",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketactivityattachmentevent",
          label: "TicketActivityAttachmentEvent",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketactivitycomment",
          label: "TicketActivityComment",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketactivitycommentevent",
          label: "TicketActivityCommentEvent",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketactivitycreateitem",
          label: "TicketActivityCreateItem",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketactivitycreateresponse",
          label: "TicketActivityCreateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketactivityevent",
          label: "TicketActivityEvent",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketactivityitemgetresponse",
          label: "TicketActivityItemGetResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketactivitylistresponse",
          label: "TicketActivityListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketactivitylogentry",
          label: "TicketActivityLogEntry",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketactivityownersummary",
          label: "TicketActivityOwnerSummary",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketactivitypartevent",
          label: "TicketActivityPartEvent",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketactivityrequest",
          label: "TicketActivityRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketactivityrevisionevent",
          label: "TicketActivityRevisionEvent",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketactivityruleexecutionevent",
          label: "TicketActivityRuleExecutionEvent",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketactivitysingleresponse",
          label: "TicketActivitySingleResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketactivityupdateresponse",
          label: "TicketActivityUpdateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketactivityworkflowlogevent",
          label: "TicketActivityWorkflowLogEvent",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketadditionaldetails",
          label: "TicketAdditionalDetails",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketapproval",
          label: "TicketApproval",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketapprovalrequest",
          label: "TicketApprovalRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketapprovalsresponse",
          label: "TicketApprovalsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketasset",
          label: "TicketAsset",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketassetlink",
          label: "TicketAssetLink",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketassetlistresponse",
          label: "TicketAssetListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketassetupdateitem",
          label: "TicketAssetUpdateItem",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketassignrequest",
          label: "TicketAssignRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketassignresponse",
          label: "TicketAssignResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketbulksetinforequest",
          label: "TicketBulkSetInfoRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketbulksetinfovalue",
          label: "TicketBulkSetInfoValue",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketcanceloptions",
          label: "TicketCancelOptions",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketcloserequest",
          label: "TicketCloseRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketcloseresponse",
          label: "TicketCloseResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketcopyrequest",
          label: "TicketCopyRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketcountresponse",
          label: "TicketCountResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketcreateasset",
          label: "TicketCreateAsset",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketcreaterequest",
          label: "TicketCreateRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketcustomfieldupdateitem",
          label: "TicketCustomFieldUpdateItem",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketcustomfieldupdaterequest",
          label: "TicketCustomFieldUpdateRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketcustomfieldupdateresponse",
          label: "TicketCustomFieldUpdateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketdeleteresponse",
          label: "TicketDeleteResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketduplicateresponse",
          label: "TicketDuplicateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketfielddefinition",
          label: "TicketFieldDefinition",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketfieldsresponse",
          label: "TicketFieldsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketfollowersresponse",
          label: "TicketFollowersResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketguestregistration",
          label: "TicketGuestRegistration",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketissueconfirmationresponse",
          label: "TicketIssueConfirmationResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketkbarticles",
          label: "TicketKbArticles",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketkbarticlesresponse",
          label: "TicketKbArticlesResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketlistresponse",
          label: "TicketListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketlocationsummary",
          label: "TicketLocationSummary",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketnextstep",
          label: "TicketNextStep",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketnextstepcreateresponse",
          label: "TicketNextStepCreateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketnextsteprequest",
          label: "TicketNextStepRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketnextstepresolveresponse",
          label: "TicketNextStepResolveResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketnextstepresponse",
          label: "TicketNextStepResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketnextsteptype",
          label: "TicketNextStepType",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketnextstepupdateresponse",
          label: "TicketNextStepUpdateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketnextstepsresponse",
          label: "TicketNextStepsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketpermission",
          label: "TicketPermission",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketprioritylevel",
          label: "TicketPriorityLevel",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketprioritylistresponse",
          label: "TicketPriorityListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketreminder",
          label: "TicketReminder",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketremindersrequest",
          label: "TicketRemindersRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketremindersresponse",
          label: "TicketRemindersResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketremindersupdateresponse",
          label: "TicketRemindersUpdateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketsearchfacetkey",
          label: "TicketSearchFacetKey",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketsearchfilter",
          label: "TicketSearchFilter",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketsearchrequest",
          label: "TicketSearchRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketsearchresponse",
          label: "TicketSearchResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketsingleresponse",
          label: "TicketSingleResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketsla",
          label: "TicketSla",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketslalistresponse",
          label: "TicketSlaListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketslasingleresponse",
          label: "TicketSlaSingleResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketslatime",
          label: "TicketSlaTime",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketsource",
          label: "TicketSource",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketsourcesresponse",
          label: "TicketSourcesResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketstartrequest",
          label: "TicketStartRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketstatsresponse",
          label: "TicketStatsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketstatus",
          label: "TicketStatus",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketstatuslistresponse",
          label: "TicketStatusListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketstatusresponse",
          label: "TicketStatusResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketstatussingleresponse",
          label: "TicketStatusSingleResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketsubtask",
          label: "TicketSubtask",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketsubtaskitemresponse",
          label: "TicketSubtaskItemResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketsubtasklistresponse",
          label: "TicketSubtaskListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketsubtaskrequest",
          label: "TicketSubtaskRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/tickettemplaterecurringschedule",
          label: "TicketTemplateRecurringSchedule",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/tickettimelineresponse",
          label: "TicketTimelineResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketundeleteresponse",
          label: "TicketUndeleteResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketupdaterequest",
          label: "TicketUpdateRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketupdateresponse",
          label: "TicketUpdateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketusersummary",
          label: "TicketUserSummary",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketworkflowstate",
          label: "TicketWorkflowState",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketworkflowstatus",
          label: "TicketWorkflowStatus",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketworkflowstepsummary",
          label: "TicketWorkflowStepSummary",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/ticketworkflowtransitionresponse",
          label: "TicketWorkflowTransitionResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/unauthorizederror",
          label: "UnauthorizedError",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/updatesubtaskgroupresponse",
          label: "UpdateSubtaskGroupResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/updateticketassetsrequest",
          label: "UpdateTicketAssetsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/updateticketdescriptionrequest",
          label: "UpdateTicketDescriptionRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/updateticketsubjectrequest",
          label: "UpdateTicketSubjectRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/user",
          label: "User",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/userlistresponse",
          label: "UserListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/usersummary",
          label: "UserSummary",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/viewcolumn",
          label: "ViewColumn",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/viewcolumnoption",
          label: "ViewColumnOption",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/viewdefinition",
          label: "ViewDefinition",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/viewfiltervalue",
          label: "ViewFilterValue",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/viewitemcreateresponse",
          label: "ViewItemCreateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/viewitemgetresponse",
          label: "ViewItemGetResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/viewitemupdateresponse",
          label: "ViewItemUpdateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/viewlistresponse",
          label: "ViewListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/viewschedule",
          label: "ViewSchedule",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/viewsharesummary",
          label: "ViewShareSummary",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/viewsort",
          label: "ViewSort",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/viewtab",
          label: "ViewTab",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/workpackage",
          label: "Workpackage",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/tickets/schemas/workpackageticket",
          label: "WorkpackageTicket",
          className: "schema",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
