import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "api/custom-fields/custom-fields-api",
    },
    {
      type: "category",
      label: "Deleting",
      link: {
        type: "doc",
        id: "api/custom-fields/custom-fields-deleting",
      },
      items: [
        {
          type: "doc",
          id: "api/custom-fields/delete-custom-field-values-for-assets",
          label: "Delete custom field values for assets",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/custom-fields/delete-custom-field-values-for-tickets",
          label: "Delete custom field values for tickets",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/custom-fields/delete-custom-field-values-for-users",
          label: "Delete custom field values for users",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/custom-fields/delete-custom-field-values-for-events",
          label: "Delete custom field values for events",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/custom-fields/delete-asset-inventory-action-custom-field-values",
          label: "Delete asset inventory action custom field values",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Discovering",
      link: {
        type: "doc",
        id: "api/custom-fields/custom-fields-discovering",
      },
      items: [
        {
          type: "doc",
          id: "api/custom-fields/get-custom-fields-for-asset",
          label: "Get custom fields for asset",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/custom-fields/get-custom-fields-for-ticket",
          label: "Get custom fields for ticket",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/custom-fields/get-custom-fields-for-user",
          label: "Get custom fields for user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/custom-fields/get-custom-fields-for-event",
          label: "Get custom fields for event",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/custom-fields/get-custom-fields-for-location",
          label: "Get custom fields for location",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/custom-fields/get-custom-fields-for-location-room",
          label: "Get custom fields for location room",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/custom-fields/get-custom-fields-for-inventory-item",
          label: "Get custom fields for inventory item",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/custom-fields/get-custom-fields-for-organization",
          label: "Get custom fields for organization",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/custom-fields/get-custom-fields-for-asset-inventory-action",
          label: "Get custom fields for asset inventory action",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Fields",
      link: {
        type: "doc",
        id: "api/custom-fields/custom-fields-fields",
      },
      items: [
        {
          type: "doc",
          id: "api/custom-fields/search-custom-fields",
          label: "Search custom fields",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/custom-fields/get-custom-field-by-id",
          label: "Get custom field by ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/custom-fields/update-custom-field",
          label: "Update custom field",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/custom-fields/delete-custom-field",
          label: "Delete custom field",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/custom-fields/create-custom-field-batch",
          label: "Create custom fields (batch)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/custom-fields/reorder-custom-fields",
          label: "Reorder custom fields",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Mappings",
      link: {
        type: "doc",
        id: "api/custom-fields/custom-fields-mappings",
      },
      items: [
        {
          type: "doc",
          id: "api/custom-fields/get-custom-field-entity-mappings",
          label: "List all custom field entity mappings",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/custom-fields/get-custom-field-entity-mapping-entity-types",
          label: "Get available entity types for mappings",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/custom-fields/get-custom-field-mapping-compatible-fields",
          label: "Get compatible target fields for mapping",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/custom-fields/check-custom-field-mapping-compatibility",
          label: "Check if two fields are compatible for mapping",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/custom-fields/batch-create-custom-field-entity-mappings",
          label: "Batch create custom field entity mappings",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/custom-fields/batch-delete-custom-field-entity-mappings",
          label: "Batch delete custom field entity mappings",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Setting",
      link: {
        type: "doc",
        id: "api/custom-fields/custom-fields-setting",
      },
      items: [
        {
          type: "doc",
          id: "api/custom-fields/upsert-asset-custom-field-values",
          label: "Upsert asset custom field values",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/custom-fields/upsert-ticket-custom-field-values",
          label: "Upsert ticket custom field values",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/custom-fields/upsert-user-custom-field-values",
          label: "Upsert user custom field values",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/custom-fields/upsert-event-custom-field-values",
          label: "Upsert event custom field values",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/custom-fields/upsert-asset-inventory-action-custom-field-values",
          label: "Upsert asset inventory action custom field values",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/custom-fields/batch-update-custom-field-product",
          label: "Batch update custom field product associations",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Types",
      link: {
        type: "doc",
        id: "api/custom-fields/custom-fields-types",
      },
      items: [
        {
          type: "doc",
          id: "api/custom-fields/list-custom-field-types",
          label: "List custom field types",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/custom-fields/search-custom-field-types",
          label: "Search custom field types",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/custom-fields/get-custom-field-type-by-id",
          label: "Get custom field type",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/custom-fields/update-custom-field-type",
          label: "Update custom field type",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/custom-fields/delete-custom-field-type",
          label: "Delete custom field type",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/custom-fields/create-custom-field-type",
          label: "Create custom field type",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/custom-fields/batch-create-custom-field-types",
          label: "Batch create custom field types",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/custom-fields/batch-update-custom-field-types",
          label: "Batch update custom field types",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/custom-fields/reorder-custom-field-types",
          label: "Reorder custom field types",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Utilities",
      link: {
        type: "doc",
        id: "api/custom-fields/custom-fields-utilities",
      },
      items: [
        {
          type: "doc",
          id: "api/custom-fields/list-custom-field-types-new",
          label: "List custom field types (alternate endpoint)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/custom-fields/update-custom-field-product",
          label: "Update custom field product association",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/custom-fields/lookup-site-by-searchable-value",
          label: "Lookup site by custom field searchable value",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Values",
      link: {
        type: "doc",
        id: "api/custom-fields/custom-fields-values",
      },
      items: [
        {
          type: "doc",
          id: "api/custom-fields/get-custom-field-values-for-asset",
          label: "Get custom field values for asset",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/custom-fields/get-custom-field-values-for-ticket",
          label: "Get custom field values for ticket",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/custom-fields/get-custom-field-values-for-user",
          label: "Get custom field values for user",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/custom-fields/get-asset-custom-field-values",
          label: "Get asset custom field values",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/custom-fields/get-ticket-custom-field-values",
          label: "Get ticket custom field values",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/custom-fields/get-user-custom-field-values",
          label: "Get user custom field values",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/custom-fields/get-event-custom-field-values",
          label: "Get event custom field values",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/custom-fields/get-asset-inventory-action-custom-field-values",
          label: "Get custom field values for asset inventory action",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Schemas",
      items: [
        {
          type: "doc",
          id: "api/custom-fields/schemas/actionresponse",
          label: "ActionResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/assetcustomfieldvalue",
          label: "AssetCustomFieldValue",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/assetcustomfieldvaluelistresponse",
          label: "AssetCustomFieldValueListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/assetinventoryactioncustomfieldvalue",
          label: "AssetInventoryActionCustomFieldValue",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/assetinventoryactioncustomfieldvaluelistresponse",
          label: "AssetInventoryActionCustomFieldValueListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/batchcustomfieldentitymappingrequest",
          label: "BatchCustomFieldEntityMappingRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/checkfieldmappingcompatibilityrequest",
          label: "CheckFieldMappingCompatibilityRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/complexcustomfieldsearchvaluelookuprequest",
          label: "ComplexCustomFieldSearchValueLookupRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/complexeditorvalues",
          label: "ComplexEditorValues",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/createcustomfieldbatchcustomfieldsnewrequest",
          label: "CreateCustomFieldBatchCustomFieldsNewRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/customfieldcreaterequest",
          label: "CustomFieldCreateRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/customfielddetail",
          label: "CustomFieldDetail",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/customfieldeditortypeid",
          label: "CustomFieldEditorTypeId",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/customfieldentitymappingentityfield",
          label: "CustomFieldEntityMappingEntityField",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/customfieldentitymappingrequest",
          label: "CustomFieldEntityMappingRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/customfieldgetresponse",
          label: "CustomFieldGetResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/customfieldlistresponse",
          label: "CustomFieldListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/customfieldproductupdaterequest",
          label: "CustomFieldProductUpdateRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/customfieldreorderrequest",
          label: "CustomFieldReorderRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/customfieldtypebatchcreaterequest",
          label: "CustomFieldTypeBatchCreateRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/customfieldtypebatchupdaterequest",
          label: "CustomFieldTypeBatchUpdateRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/customfieldtypecreaterequest",
          label: "CustomFieldTypeCreateRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/customfieldtypecreateresponse",
          label: "CustomFieldTypeCreateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/customfieldtypedeleteresponse",
          label: "CustomFieldTypeDeleteResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/customfieldtypedetail",
          label: "CustomFieldTypeDetail",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/customfieldtypelistresponse",
          label: "CustomFieldTypeListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/customfieldtypereorderrequest",
          label: "CustomFieldTypeReorderRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/customfieldtypesummary",
          label: "CustomFieldTypeSummary",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/customfieldtypeupdaterequest",
          label: "CustomFieldTypeUpdateRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/customfieldtypeupdateresponse",
          label: "CustomFieldTypeUpdateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/customfieldupdaterequest",
          label: "CustomFieldUpdateRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/customfieldupdateresponse",
          label: "CustomFieldUpdateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/deletecustomfieldvaluesrequest",
          label: "DeleteCustomFieldValuesRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/entityfiltervalue",
          label: "EntityFilterValue",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/errorresponse",
          label: "ErrorResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/eventcustomfieldvalue",
          label: "EventCustomFieldValue",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/eventcustomfieldvaluelistresponse",
          label: "EventCustomFieldValueListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/filtermatch",
          label: "FilterMatch",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/filtervalue",
          label: "FilterValue",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/filtervaluesaverequest",
          label: "FilterValueSaveRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/forbiddenerror",
          label: "ForbiddenError",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/getcustomfieldmappingcompatiblefieldsrequest",
          label: "GetCustomFieldMappingCompatibleFieldsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/getcustomfieldtypesrequest",
          label: "GetCustomFieldTypesRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/getcustomfieldsforassetinventoryactionrequest",
          label: "GetCustomFieldsForAssetInventoryActionRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/getcustomfieldsforassetrequest",
          label: "GetCustomFieldsForAssetRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/getcustomfieldsforeventrequest",
          label: "GetCustomFieldsForEventRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/getcustomfieldsforinventoryitemrequest",
          label: "GetCustomFieldsForInventoryItemRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/getcustomfieldsforlocationrequest",
          label: "GetCustomFieldsForLocationRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/getcustomfieldsforlocationroomrequest",
          label: "GetCustomFieldsForLocationRoomRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/getcustomfieldsfororganizationrequest",
          label: "GetCustomFieldsForOrganizationRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/getcustomfieldsforticketrequest",
          label: "GetCustomFieldsForTicketRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/getcustomfieldsforuserrequest",
          label: "GetCustomFieldsForUserRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/getcustomfieldsrequest",
          label: "GetCustomFieldsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/itemcreateresponse",
          label: "ItemCreateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/itemdeleteresponse",
          label: "ItemDeleteResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/itemgetresponse",
          label: "ItemGetResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/itemupdateresponse",
          label: "ItemUpdateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/listcreateresponse",
          label: "ListCreateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/listdeleteresponse",
          label: "ListDeleteResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/listgetresponse",
          label: "ListGetResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/listupdateresponse",
          label: "ListUpdateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/notfounderror",
          label: "NotFoundError",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/pagingmetadata",
          label: "PagingMetadata",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/pagingoptions",
          label: "PagingOptions",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/responseenvelope",
          label: "ResponseEnvelope",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/responselog",
          label: "ResponseLog",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/sitelookupbysearchablevalueresponse",
          label: "SiteLookupBySearchableValueResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/softvalidationerror",
          label: "SoftValidationError",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/sortoptions",
          label: "SortOptions",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/ticketcustomfieldvalue",
          label: "TicketCustomFieldValue",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/ticketcustomfieldvaluelistresponse",
          label: "TicketCustomFieldValueListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/unauthorizederror",
          label: "UnauthorizedError",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/upsertassetcustomfieldvaluesrequest",
          label: "UpsertAssetCustomFieldValuesRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/upsertassetinventoryactioncustomfieldvaluesrequest",
          label: "UpsertAssetInventoryActionCustomFieldValuesRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/upsertcustomfieldvaluesresponse",
          label: "UpsertCustomFieldValuesResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/upserteventcustomfieldvaluesrequest",
          label: "UpsertEventCustomFieldValuesRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/upsertticketcustomfieldvaluesrequest",
          label: "UpsertTicketCustomFieldValuesRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/upsertusercustomfieldvaluesrequest",
          label: "UpsertUserCustomFieldValuesRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/usercustomfieldvalue",
          label: "UserCustomFieldValue",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/usercustomfieldvaluelistresponse",
          label: "UserCustomFieldValueListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/uuidlist",
          label: "UuidList",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/custom-fields/schemas/validationerror",
          label: "ValidationError",
          className: "schema",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
