import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "api/locations/locations-api",
    },
    {
      type: "category",
      label: "Details",
      link: {
        type: "doc",
        id: "api/locations/locations-details",
      },
      items: [
        {
          type: "doc",
          id: "api/locations/get-location-by-id-v-2",
          label: "Get location by ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/locations/get-location-address-v-2",
          label: "Get location address",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/locations/get-address-by-id-v-2",
          label: "Get address by ID",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Files",
      link: {
        type: "doc",
        id: "api/locations/locations-files",
      },
      items: [
        {
          type: "doc",
          id: "api/locations/get-location-floorplans-v-2",
          label: "Get location floorplans",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/locations/update-location-floorplans-v-2",
          label: "Update location floorplans",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/locations/get-location-images-v-2",
          label: "Get location images",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/locations/update-location-images-v-2",
          label: "Update location images",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Filtering",
      link: {
        type: "doc",
        id: "api/locations/locations-filtering",
      },
      items: [
        {
          type: "doc",
          id: "api/locations/get-location-ids-for-filter-sets-v-2",
          label: "Get location IDs for filter sets",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Managing",
      link: {
        type: "doc",
        id: "api/locations/locations-managing",
      },
      items: [
        {
          type: "doc",
          id: "api/locations/create-location-v-2",
          label: "Create location",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/locations/update-location-v-2",
          label: "Update location",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/locations/delete-location-v-2",
          label: "Delete location",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/locations/undelete-location-v-2",
          label: "Restore deleted location",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/locations/migrate-location-v-2",
          label: "Migrate location entities",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Rooms",
      link: {
        type: "doc",
        id: "api/locations/locations-rooms",
      },
      items: [
        {
          type: "doc",
          id: "api/locations/create-location-room",
          label: "Create a room",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/locations/create-location-rooms-batch",
          label: "Create multiple rooms",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/locations/query-location-rooms",
          label: "Query rooms",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/locations/query-location-rooms-for-user",
          label: "Query rooms for current user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/locations/query-location-rooms-by-location-id",
          label: "Query rooms by location",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/locations/get-location-room-by-id",
          label: "Get room by ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/locations/update-location-room",
          label: "Update a room",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/locations/delete-location-room",
          label: "Delete a room",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/locations/update-location-rooms-batch",
          label: "Update multiple rooms",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/locations/delete-location-rooms-batch",
          label: "Delete multiple rooms",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/locations/undelete-location-room",
          label: "Undelete a room",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/locations/get-location-room-status-type-by-id",
          label: "Get room status type by ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/locations/get-all-location-room-status-types",
          label: "Get all room status types",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Rooms Availability",
      link: {
        type: "doc",
        id: "api/locations/locations-rooms-availability",
      },
      items: [
        {
          type: "doc",
          id: "api/locations/get-location-room-available-times",
          label: "Get room available times",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/locations/update-location-room-available-times",
          label: "Update room available times",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/locations/bulk-set-location-room-available-times",
          label: "Bulk update room available times",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Rooms Bulk",
      link: {
        type: "doc",
        id: "api/locations/locations-rooms-bulk",
      },
      items: [
        {
          type: "doc",
          id: "api/locations/bulk-delete-location-rooms",
          label: "Bulk delete rooms",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/locations/bulk-set-location-room-types",
          label: "Bulk set room types",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/locations/bulk-set-location-room-lead-time",
          label: "Bulk set room lead time",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/locations/bulk-set-location-room-external-availability",
          label: "Bulk set external availability",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Rooms Files",
      link: {
        type: "doc",
        id: "api/locations/locations-rooms-files",
      },
      items: [
        {
          type: "doc",
          id: "api/locations/get-location-room-layouts",
          label: "Get room layouts",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/locations/update-location-room-layouts",
          label: "Update room layouts",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/locations/get-location-room-images",
          label: "Get room images",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/locations/update-location-room-images",
          label: "Update room images",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Searching",
      link: {
        type: "doc",
        id: "api/locations/locations-searching",
      },
      items: [
        {
          type: "doc",
          id: "api/locations/get-my-locations-v-2",
          label: "Get my locations",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/locations/get-my-locations-filtered-v-2",
          label: "Get my locations (filtered)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/locations/get-my-locations-view-v-2",
          label: "Get my locations (view)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/locations/get-my-locations-view-filtered-v-2",
          label: "Get my locations (view, filtered)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/locations/get-my-locations-manage-v-2",
          label: "Get my locations with manage permission",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/locations/get-my-locations-manage-filtered-v-2",
          label: "Get my locations with manage permission (filtered)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/locations/get-user-locations-v-2",
          label: "Get user locations",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/locations/get-user-locations-filtered-v-2",
          label: "Get user locations (filtered)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/locations/get-user-locations-view-v-2",
          label: "Get user locations (view)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/locations/get-user-locations-view-filtered-v-2",
          label: "Get user locations (view, filtered)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/locations/get-current-user-locations-v-2",
          label: "Get current user locations",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/locations/get-current-user-locations-filtered-v-2",
          label: "Get current user locations (filtered)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/locations/get-current-user-locations-view-v-2",
          label: "Get current user locations (view)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/locations/get-current-user-locations-view-filtered-v-2",
          label: "Get current user locations (view, filtered)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/locations/get-all-site-locations-v-2",
          label: "Get all site locations",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/locations/get-all-site-locations-filtered-v-2",
          label: "Get all site locations (filtered)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/locations/get-site-locations-by-site-id-v-2",
          label: "Get locations by site ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/locations/get-site-locations-by-site-id-filtered-v-2",
          label: "Get locations by site ID (filtered)",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Schemas",
      items: [
        {
          type: "doc",
          id: "api/locations/schemas/actionresponse",
          label: "ActionResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/locations/schemas/address",
          label: "Address",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/locations/schemas/addressitemresponse",
          label: "AddressItemResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/locations/schemas/bulkjoblocationroomdeleterequest",
          label: "BulkJobLocationRoomDeleteRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/locations/schemas/bulklocationroomavailabletimesrequest",
          label: "BulkLocationRoomAvailableTimesRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/locations/schemas/bulklocationroomrequest",
          label: "BulkLocationRoomRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/locations/schemas/bulkroomdeleterequest",
          label: "BulkRoomDeleteRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/locations/schemas/bulkroomexternalavailabilityrequest",
          label: "BulkRoomExternalAvailabilityRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/locations/schemas/bulkroomleadtimerequest",
          label: "BulkRoomLeadTimeRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/locations/schemas/bulkroomtyperequest",
          label: "BulkRoomTypeRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/locations/schemas/complexeditorvalues",
          label: "ComplexEditorValues",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/locations/schemas/datafilter",
          label: "DataFilter",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/locations/schemas/datafilteroperations",
          label: "DataFilterOperations",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/locations/schemas/entityfiledetail",
          label: "EntityFileDetail",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/locations/schemas/entityfiledetaillistresponse",
          label: "EntityFileDetailListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/locations/schemas/forbiddenerror",
          label: "ForbiddenError",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/locations/schemas/getidsforfiltersetrequest",
          label: "GetIdsForFilterSetRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/locations/schemas/getlocationroomsrequest",
          label: "GetLocationRoomsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/locations/schemas/getuserlocationsrequest",
          label: "GetUserLocationsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/locations/schemas/guiditemresponse",
          label: "GuidItemResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/locations/schemas/guidlistupdateresponse",
          label: "GuidListUpdateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/locations/schemas/idsforfiltersetslistresponse",
          label: "IdsForFilterSetsListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/locations/schemas/idsforfiltersetsresponse",
          label: "IdsForFilterSetsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/locations/schemas/itemdeleteresponse",
          label: "ItemDeleteResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/locations/schemas/listdeleteresponse",
          label: "ListDeleteResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/locations/schemas/location",
          label: "Location",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/locations/schemas/locationcreateresponse",
          label: "LocationCreateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/locations/schemas/locationcustomfieldvalue",
          label: "LocationCustomFieldValue",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/locations/schemas/locationdeleteresponse",
          label: "LocationDeleteResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/locations/schemas/locationitemresponse",
          label: "LocationItemResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/locations/schemas/locationlistresponse",
          label: "LocationListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/locations/schemas/locationroom",
          label: "LocationRoom",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/locations/schemas/locationroomavailabletime",
          label: "LocationRoomAvailableTime",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/locations/schemas/locationroomavailabletimelistresponse",
          label: "LocationRoomAvailableTimeListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/locations/schemas/locationroomavailabletimelistupdateresponse",
          label: "LocationRoomAvailableTimeListUpdateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/locations/schemas/locationroomcustomfieldvalue",
          label: "LocationRoomCustomFieldValue",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/locations/schemas/locationroomitemcreateresponse",
          label: "LocationRoomItemCreateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/locations/schemas/locationroomitemresponse",
          label: "LocationRoomItemResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/locations/schemas/locationroomitemupdateresponse",
          label: "LocationRoomItemUpdateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/locations/schemas/locationroomlistcreateresponse",
          label: "LocationRoomListCreateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/locations/schemas/locationroomlistresponse",
          label: "LocationRoomListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/locations/schemas/locationroomstatustype",
          label: "LocationRoomStatusType",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/locations/schemas/locationroomstatustypeitemresponse",
          label: "LocationRoomStatusTypeItemResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/locations/schemas/locationroomstatustypelistresponse",
          label: "LocationRoomStatusTypeListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/locations/schemas/locationstatustype",
          label: "LocationStatusType",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/locations/schemas/locationtype",
          label: "LocationType",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/locations/schemas/locationupdateresponse",
          label: "LocationUpdateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/locations/schemas/locationwithpermissionlistresponse",
          label: "LocationWithPermissionListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/locations/schemas/locationwithuserpermission",
          label: "LocationWithUserPermission",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/locations/schemas/migratelocationrequest",
          label: "MigrateLocationRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/locations/schemas/notfounderror",
          label: "NotFoundError",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/locations/schemas/pagingmetadata",
          label: "PagingMetadata",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/locations/schemas/pagingoptions",
          label: "PagingOptions",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/locations/schemas/requestoptions",
          label: "RequestOptions",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/locations/schemas/softvalidationerror",
          label: "SoftValidationError",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/locations/schemas/sortoptions",
          label: "SortOptions",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/locations/schemas/unauthorizederror",
          label: "UnauthorizedError",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/locations/schemas/updateentityfiledetailsrequest",
          label: "UpdateEntityFileDetailsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/locations/schemas/updatelocationrequest",
          label: "UpdateLocationRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/locations/schemas/updatelocationroomavailabletimerequest",
          label: "UpdateLocationRoomAvailableTimeRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/locations/schemas/updatelocationroomrequest",
          label: "UpdateLocationRoomRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/locations/schemas/validationerror",
          label: "ValidationError",
          className: "schema",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
