import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "api/assets/assets-api",
    },
    {
      type: "category",
      label: "Activity",
      link: {
        type: "doc",
        id: "api/assets/assets-activity",
      },
      items: [
        {
          type: "doc",
          id: "api/assets/query-asset-changes",
          label: "Query asset change history",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/assets/get-asset-activities",
          label: "Get asset activity timeline",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/assets/get-asset-change",
          label: "Get asset change detail",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/assets/get-asset-change-post",
          label: "Get asset change detail (POST)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/assets/get-changed-assets",
          label: "Get changed assets",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/assets/get-changed-assets-count",
          label: "Get count of changed assets",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/assets/create-asset-verification",
          label: "Verify asset",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/assets/bulk-create-asset-verifications",
          label: "Bulk create verifications",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/assets/search-asset-verifications",
          label: "Search asset verifications",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/assets/get-asset-verifications-for-asset",
          label: "Get verifications for asset",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/assets/get-asset-verification-by-id",
          label: "Get verification by ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/assets/update-asset-verification",
          label: "Update verification",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/assets/delete-asset-verification",
          label: "Delete verification",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/assets/bulk-delete-asset-verifications",
          label: "Bulk delete verifications",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/assets/create-my-classes-asset-verification",
          label: "Create My Classes verification",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/assets/update-my-classes-asset-verification",
          label: "Update My Classes verification",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Bulk",
      link: {
        type: "doc",
        id: "api/assets/assets-bulk",
      },
      items: [
        {
          type: "doc",
          id: "api/assets/bulk-set-asset-owner",
          label: "Bulk set asset owners",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/assets/bulk-set-locked-to-id",
          label: "Bulk set locked-to-id",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/assets/bulk-unlink-assets",
          label: "Bulk unlink assets",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/assets/bulk-verify-assets",
          label: "Bulk verify assets",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/assets/bulk-delete-assets",
          label: "Bulk delete assets",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/assets/bulk-submit-tickets-from-templates",
          label: "Bulk submit tickets from templates",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/assets/bulk-update-assets",
          label: "Bulk update assets",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/assets/bulk-add-to-ticket-template",
          label: "Bulk add assets to ticket template",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/assets/bulk-generate-from-template",
          label: "Bulk generate assets from template",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/assets/bulk-asset-copy",
          label: "Bulk copy assets",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/assets/bulk-set-asset-info",
          label: "Bulk update asset custom fields",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/assets/bulk-set-asset-location",
          label: "Bulk update asset location",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/assets/bulk-delete-asset-types",
          label: "Bulk Delete Asset Types",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/assets/bulk-set-asset-status",
          label: "Bulk set asset status",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Checkout",
      link: {
        type: "doc",
        id: "api/assets/assets-checkout",
      },
      items: [
        {
          type: "doc",
          id: "api/assets/checkout-or-transfer-asset",
          label: "Checkout or transfer asset",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/assets/checkin-asset",
          label: "Check in asset",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/assets/exchange-asset",
          label: "Exchange asset",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/assets/get-asset-checkout",
          label: "Get asset checkout",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/assets/get-asset-checkout-post",
          label: "Get asset checkout (POST)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/assets/get-asset-checkout-for-owner",
          label: "Get checkout for asset owner",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/assets/get-asset-checkouts-by-ids",
          label: "Get asset checkouts by IDs",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/assets/get-asset-checkouts-by-query",
          label: "List asset checkouts",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/assets/get-asset-checkout-transactions",
          label: "List asset checkout transactions",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/assets/get-recent-asset-checkout-transactions",
          label: "Recent checkout activity",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/assets/get-overdue-asset-checkouts",
          label: "Get overdue checkouts for asset",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/assets/delete-asset-checkout",
          label: "Delete checkout",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/assets/delete-asset-checkouts-by-ids",
          label: "Delete checkouts by IDs",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/assets/delete-asset-checkouts-by-query",
          label: "Delete checkouts by query",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/assets/update-asset-checkouts-by-ids",
          label: "Bulk update checkouts by IDs",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/assets/update-asset-checkouts-by-query",
          label: "Bulk update checkouts by query",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/assets/update-asset-exchange-transaction",
          label: "Update checkout transaction",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/assets/undo-asset-exchange-transaction",
          label: "Undo checkout transaction",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Cost",
      link: {
        type: "doc",
        id: "api/assets/assets-cost",
      },
      items: [
        {
          type: "doc",
          id: "api/assets/get-asset-total-cost",
          label: "Get asset total cost",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/assets/get-asset-valuation",
          label: "Get asset valuation",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/assets/get-aggregated-asset-cost-values",
          label: "Get aggregated asset cost values",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/assets/get-nsa-asset-average-cost",
          label: "Get NSA average cost",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Creating",
      link: {
        type: "doc",
        id: "api/assets/assets-creating",
      },
      items: [
        {
          type: "doc",
          id: "api/assets/create-asset",
          label: "Create a new asset",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/assets/create-asset-view",
          label: "Create asset view",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/assets/generate-asset-tag",
          label: "Generate asset tag",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Details",
      link: {
        type: "doc",
        id: "api/assets/assets-details",
      },
      items: [
        {
          type: "doc",
          id: "api/assets/get-asset-by-id",
          label: "Get asset by ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/assets/get-asset-by-tag",
          label: "Get asset by asset tag",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/assets/get-asset-by-serial",
          label: "Get asset by serial number",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Updating",
      link: {
        type: "doc",
        id: "api/assets/assets-updating",
      },
      items: [
        {
          type: "doc",
          id: "api/assets/update-asset",
          label: "Update asset",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/assets/delete-asset",
          label: "Delete asset",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/assets/update-asset-view",
          label: "Update asset view",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/assets/set-asset-location",
          label: "Set asset location",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/assets/update-asset-view-sort",
          label: "Update asset view sort",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/assets/set-asset-owner",
          label: "Assign or unassign asset owner",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/assets/take-asset-ownership",
          label: "Take ownership of asset",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/assets/set-asset-owner-advanced-deployment-swap",
          label: "Swap asset owner via advanced deployment",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/assets/remove-asset-owner",
          label: "Remove asset owner",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/assets/set-asset-status",
          label: "Set asset status",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/assets/remove-user-asset",
          label: "Remove asset from user",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/assets/undelete-asset",
          label: "Restore deleted asset",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/assets/merge-assets",
          label: "Merge assets",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Files",
      link: {
        type: "doc",
        id: "api/assets/assets-files",
      },
      items: [
        {
          type: "doc",
          id: "api/assets/get-asset-files",
          label: "Get asset files",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/assets/add-asset-files",
          label: "Add files to asset",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/assets/delete-asset-file",
          label: "Delete asset file",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Viewing",
      link: {
        type: "doc",
        id: "api/assets/assets-viewing",
      },
      items: [
        {
          type: "doc",
          id: "api/assets/get-asset-view",
          label: "Get asset view",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/assets/list-asset-views",
          label: "List asset views",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Lifecycle",
      link: {
        type: "doc",
        id: "api/assets/assets-lifecycle",
      },
      items: [
        {
          type: "doc",
          id: "api/assets/delete-asset-view",
          label: "Delete asset view",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Linked",
      link: {
        type: "doc",
        id: "api/assets/assets-linked",
      },
      items: [
        {
          type: "doc",
          id: "api/assets/get-linked-assets",
          label: "Get linked assets",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/assets/add-linked-assets",
          label: "Link assets to parent",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/assets/delete-linked-assets",
          label: "Unlink assets from parent",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/assets/bulk-delete-linked-assets",
          label: "Bulk delete linked assets",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Searching",
      link: {
        type: "doc",
        id: "api/assets/assets-searching",
      },
      items: [
        {
          type: "doc",
          id: "api/assets/list-all-assets",
          label: "List assets",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/assets/search-assets",
          label: "Search assets",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/assets/search-assets-by-asset-tag",
          label: "Search assets by asset tag",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/assets/search-assets-by-serial",
          label: "Search assets by serial",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/assets/search-spare-pool-assets",
          label: "Search spare pool assets",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/assets/keyword-search-assets",
          label: "Keyword search assets",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/assets/list-assets-by-room",
          label: "List room assets",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/assets/list-assets-by-storage-unit",
          label: "List assets by storage unit",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/assets/list-assets-by-status-type",
          label: "List assets by status type",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/assets/get-assets-by-name",
          label: "Search assets by name",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/assets/get-assets-by-type",
          label: "Get assets by type",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/assets/get-assets-by-type-and-location",
          label: "Get assets by type and location",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/assets/get-asset-ids-for-filter-sets",
          label: "Resolve asset IDs for filter sets",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/assets/get-assets-for-user-by-type",
          label: "Get user's assets by type",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/assets/get-my-assets-by-type",
          label: "Get my assets by type",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/assets/get-assets-for-user-current",
          label: "Get a user's currently assigned assets",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/assets/get-my-assets",
          label: "Get my currently assigned assets",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/assets/get-facility-assets-by-location",
          label: "Get facility assets at location",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/assets/get-asset-stats-by-location",
          label: "Get asset statistics by location",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/assets/count-assets",
          label: "Count assets",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/assets/get-user-favorite-assets",
          label: "Get a user's favorite assets",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/assets/add-asset-favorite",
          label: "Add asset to favorites",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/assets/remove-asset-favorite",
          label: "Remove asset from favorites",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/assets/export-assets-by-type",
          label: "Export assets by type",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Types",
      link: {
        type: "doc",
        id: "api/assets/assets-types",
      },
      items: [
        {
          type: "doc",
          id: "api/assets/list-asset-types",
          label: "List asset types",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/assets/list-asset-types-post",
          label: "List asset types (POST)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/assets/create-asset-type",
          label: "Create Asset Type",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/assets/get-asset-type",
          label: "Get asset type by ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/assets/update-asset-type",
          label: "Update Asset Type",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/assets/get-available-asset-categories",
          label: "Get available asset categories for site",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/assets/add-category-to-site",
          label: "Add category to site",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/assets/remove-category-from-site",
          label: "Remove category from site",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/assets/list-asset-funding-types",
          label: "Get Asset Funding Types",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/assets/get-model-visibility",
          label: "Get model visibility",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/assets/list-asset-status-types",
          label: "List asset status types",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/assets/list-asset-status-types-post",
          label: "List asset status types (POST)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/assets/get-asset-status-type",
          label: "Get asset status type",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/assets/list-asset-inventory-types",
          label: "List asset inventory types",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/assets/list-asset-inventory-types-post",
          label: "List asset inventory types (POST)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/assets/get-asset-inventory-type",
          label: "Get asset inventory type by ID",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Schemas",
      items: [
        {
          type: "doc",
          id: "api/assets/schemas/actionresponse",
          label: "ActionResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/addassetfilesrequest",
          label: "AddAssetFilesRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/address",
          label: "Address",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/asset",
          label: "Asset",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assetactivity",
          label: "AssetActivity",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assetactivitytimelineresponse",
          label: "AssetActivityTimelineResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assetaggregationcacheentry",
          label: "AssetAggregationCacheEntry",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assetaggregationcacheentryresponse",
          label: "AssetAggregationCacheEntryResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assetbulksetinforequest",
          label: "AssetBulkSetInfoRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assetbulksetinfovalue",
          label: "AssetBulkSetInfoValue",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assetbulksetlocationrequest",
          label: "AssetBulkSetLocationRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assetcategorysiteoptionsrequest",
          label: "AssetCategorySiteOptionsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assetcategorysummary",
          label: "AssetCategorySummary",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assetchange",
          label: "AssetChange",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assetchangeitemresponse",
          label: "AssetChangeItemResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assetchangelistresponse",
          label: "AssetChangeListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assetchangedcountresponse",
          label: "AssetChangedCountResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assetcheckinrequest",
          label: "AssetCheckinRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assetcheckout",
          label: "AssetCheckout",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assetcheckoutitemresponse",
          label: "AssetCheckoutItemResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assetcheckoutlistresponse",
          label: "AssetCheckoutListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assetcheckoutrequest",
          label: "AssetCheckoutRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assetcheckouttransaction",
          label: "AssetCheckoutTransaction",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assetcheckouttransactionlistresponse",
          label: "AssetCheckoutTransactionListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assetcostitem",
          label: "AssetCostItem",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assetcountresponse",
          label: "AssetCountResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assetcreateresponse",
          label: "AssetCreateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assetcustomfieldvalue",
          label: "AssetCustomFieldValue",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assetdatamappinglookup",
          label: "AssetDataMappingLookup",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assetdatamappingsource",
          label: "AssetDataMappingSource",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assetdatamappings",
          label: "AssetDataMappings",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assetexchangerequest",
          label: "AssetExchangeRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assetexchangetransaction",
          label: "AssetExchangeTransaction",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assetexchangetransactiondto",
          label: "AssetExchangeTransactionDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assetexchangetransactionlistresponse",
          label: "AssetExchangeTransactionListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assetexchangetransactionresponse",
          label: "AssetExchangeTransactionResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assetfiltermatchlistrequest",
          label: "AssetFilterMatchListRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assetfundingtype",
          label: "AssetFundingType",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assetfundingtypelistresponse",
          label: "AssetFundingTypeListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assetinventoryaction",
          label: "AssetInventoryAction",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assetinventoryoptions",
          label: "AssetInventoryOptions",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assetinventorytransactioncheckout",
          label: "AssetInventoryTransactionCheckout",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assetinventorytype",
          label: "AssetInventoryType",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assetinventorytypeitemresponse",
          label: "AssetInventoryTypeItemResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assetinventorytypelistresponse",
          label: "AssetInventoryTypeListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assetitemresponse",
          label: "AssetItemResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assetmanualrevisionentry",
          label: "AssetManualRevisionEntry",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assetmanufacturersummary",
          label: "AssetManufacturerSummary",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assetmodelsummary",
          label: "AssetModelSummary",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assetmodelvisibilityresponse",
          label: "AssetModelVisibilityResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assetownersummary",
          label: "AssetOwnerSummary",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assetsaveoptions",
          label: "AssetSaveOptions",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assetsearchfacetkey",
          label: "AssetSearchFacetKey",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assetsearchfilter",
          label: "AssetSearchFilter",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assetsearchmetadata",
          label: "AssetSearchMetadata",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assetsearchrequest",
          label: "AssetSearchRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assetsearchresponse",
          label: "AssetSearchResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assetstatussummary",
          label: "AssetStatusSummary",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assetstatustype",
          label: "AssetStatusType",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assetstatustypelistresponse",
          label: "AssetStatusTypeListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assetstatustyperesponse",
          label: "AssetStatusTypeResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assettotalcost",
          label: "AssetTotalCost",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assettotalcostfull",
          label: "AssetTotalCostFull",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assettotalcostresponse",
          label: "AssetTotalCostResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assettype",
          label: "AssetType",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assettypebulkdeleteresponse",
          label: "AssetTypeBulkDeleteResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assettypecreateresponse",
          label: "AssetTypeCreateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assettypeitemresponse",
          label: "AssetTypeItemResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assettypelistresponse",
          label: "AssetTypeListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assettypesummary",
          label: "AssetTypeSummary",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assetupdaterequest",
          label: "AssetUpdateRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assetupdateresponse",
          label: "AssetUpdateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assetvaluation",
          label: "AssetValuation",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assetvaluationperiod",
          label: "AssetValuationPeriod",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assetvaluationresponse",
          label: "AssetValuationResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assetverification",
          label: "AssetVerification",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assetverificationbulkcreateresponse",
          label: "AssetVerificationBulkCreateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assetverificationcreaterequest",
          label: "AssetVerificationCreateRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assetverificationcreateresponse",
          label: "AssetVerificationCreateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assetverificationitemresponse",
          label: "AssetVerificationItemResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assetverificationlistresponse",
          label: "AssetVerificationListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/assetverificationsummary",
          label: "AssetVerificationSummary",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/bulkaddtotickettemplaterequest",
          label: "BulkAddToTicketTemplateRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/bulkassetcheckoutupdateresponse",
          label: "BulkAssetCheckoutUpdateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/bulkassetoperationitem",
          label: "BulkAssetOperationItem",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/bulkassetoperationrequest",
          label: "BulkAssetOperationRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/bulkassettypedeleterequest",
          label: "BulkAssetTypeDeleteRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/bulkcopyassetrequest",
          label: "BulkCopyAssetRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/bulkdataoperationitemresponse",
          label: "BulkDataOperationItemResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/bulkdataoperationresponse",
          label: "BulkDataOperationResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/bulkdeleteassettyperequest",
          label: "BulkDeleteAssetTypeRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/bulkdeleteassetsrequest",
          label: "BulkDeleteAssetsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/bulksetassetownerrequest",
          label: "BulkSetAssetOwnerRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/bulksetassetownerresponse",
          label: "BulkSetAssetOwnerResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/bulksetassetstatusrequest",
          label: "BulkSetAssetStatusRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/bulksubmitticketsfromtemplatesrequest",
          label: "BulkSubmitTicketsFromTemplatesRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/bulkunlinkassetsrequest",
          label: "BulkUnlinkAssetsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/bulkunlinkassetsresponse",
          label: "BulkUnlinkAssetsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/bulkverifyassetsrequest",
          label: "BulkVerifyAssetsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/categoryroles",
          label: "CategoryRoles",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/categoryroleslistresponse",
          label: "CategoryRolesListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/complexeditorvalues",
          label: "ComplexEditorValues",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/createcloneentityrequest",
          label: "CreateCloneEntityRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/customfieldeditortypeid",
          label: "CustomFieldEditorTypeId",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/datafilter",
          label: "DataFilter",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/datafilteroperations",
          label: "DataFilterOperations",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/department",
          label: "Department",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/employmentstatus",
          label: "EmploymentStatus",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/entitysiteoption",
          label: "EntitySiteOption",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/errorresponse",
          label: "ErrorResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/event",
          label: "Event",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/eventstatustype",
          label: "EventStatusType",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/eventtype",
          label: "EventType",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/file",
          label: "File",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/filelistresponse",
          label: "FileListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/filetype",
          label: "FileType",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/filtermatch",
          label: "FilterMatch",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/filtervalue",
          label: "FilterValue",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/forbiddenerror",
          label: "ForbiddenError",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/genericobject",
          label: "GenericObject",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/getassetchangesrequest",
          label: "GetAssetChangesRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/getassetcheckoutsrequest",
          label: "GetAssetCheckoutsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/getassetinventorytypesrequest",
          label: "GetAssetInventoryTypesRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/getassetstatustypesrequest",
          label: "GetAssetStatusTypesRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/getassettypesrequest",
          label: "GetAssetTypesRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/getassetverificationsrequest",
          label: "GetAssetVerificationsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/getidsforfiltersetrequest",
          label: "GetIdsForFilterSetRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/getoverdueassetcheckoutsrequest",
          label: "GetOverdueAssetCheckoutsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/guiditemresponse",
          label: "GuidItemResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/idsforfiltersetsresponse",
          label: "IdsForFilterSetsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/internalservererror",
          label: "InternalServerError",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/itemcreateresponse",
          label: "ItemCreateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/itemdeleteresponse",
          label: "ItemDeleteResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/itemgetresponse",
          label: "ItemGetResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/itemupdateresponse",
          label: "ItemUpdateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/keywordsearchassetsrequest",
          label: "KeywordSearchAssetsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/linkedasset",
          label: "LinkedAsset",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/linkedassetlistrequest",
          label: "LinkedAssetListRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/linkedassetlistresponse",
          label: "LinkedAssetListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/listdeleteresponse",
          label: "ListDeleteResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/listgetresponse",
          label: "ListGetResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/location",
          label: "Location",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/locationcustomfieldvalue",
          label: "LocationCustomFieldValue",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/locationroom",
          label: "LocationRoom",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/locationroomavailabletime",
          label: "LocationRoomAvailableTime",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/locationroomcustomfieldvalue",
          label: "LocationRoomCustomFieldValue",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/locationstat",
          label: "LocationStat",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/locationstatlistresponse",
          label: "LocationStatListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/locationstatustype",
          label: "LocationStatusType",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/locationtype",
          label: "LocationType",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/nsaaveragedistrictpurchaseprice",
          label: "NSAAverageDistrictPurchasePrice",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/nsaaveragedistrictpurchasepricelistresponse",
          label: "NSAAverageDistrictPurchasePriceListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/newassettag",
          label: "NewAssetTag",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/newassettagresponse",
          label: "NewAssetTagResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/notfounderror",
          label: "NotFoundError",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/organization",
          label: "Organization",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/organizationcustomfieldvalue",
          label: "OrganizationCustomFieldValue",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/organizationstatustype",
          label: "OrganizationStatusType",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/organizationtype",
          label: "OrganizationType",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/pagingmetadata",
          label: "PagingMetadata",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/pagingoptions",
          label: "PagingOptions",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/pagingresponse",
          label: "PagingResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/ratelimiterror",
          label: "RateLimitError",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/requestoptionparameter",
          label: "RequestOptionParameter",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/requestoptions",
          label: "RequestOptions",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/responseenvelope",
          label: "ResponseEnvelope",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/responselog",
          label: "ResponseLog",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/role",
          label: "Role",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/setassetlocationrequest",
          label: "SetAssetLocationRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/setassetownerrequest",
          label: "SetAssetOwnerRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/setassetslockedtoidrequest",
          label: "SetAssetsLockedToIdRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/simpleuser",
          label: "SimpleUser",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/site",
          label: "Site",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/softvalidationerror",
          label: "SoftValidationError",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/sortoptions",
          label: "SortOptions",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/source",
          label: "Source",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/sparepoolassetsearchfilter",
          label: "SparePoolAssetSearchFilter",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/sparepoolassetsearchrequest",
          label: "SparePoolAssetSearchRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/sparepoolassetsearchresponse",
          label: "SparePoolAssetSearchResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/sparepoolassetsummary",
          label: "SparePoolAssetSummary",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/tickettemplate",
          label: "TicketTemplate",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/tickettemplateasset",
          label: "TicketTemplateAsset",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/tickettemplatebody",
          label: "TicketTemplateBody",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/tickettemplatecustomfieldvalue",
          label: "TicketTemplateCustomFieldValue",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/tickettemplaterecurringschedule",
          label: "TicketTemplateRecurringSchedule",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/tickettemplateschedule",
          label: "TicketTemplateSchedule",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/unauthorizederror",
          label: "UnauthorizedError",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/updateassetcheckoutrequest",
          label: "UpdateAssetCheckoutRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/updateassetcheckoutsbyidsrequest",
          label: "UpdateAssetCheckoutsByIdsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/updateassetcheckoutsrequest",
          label: "UpdateAssetCheckoutsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/updateassetexchangetransactionrequest",
          label: "UpdateAssetExchangeTransactionRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/updateassettyperequest",
          label: "UpdateAssetTypeRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/updateassetverificationrequest",
          label: "UpdateAssetVerificationRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/user",
          label: "User",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/usercustomfieldvalue",
          label: "UserCustomFieldValue",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/userdatamappinglookup",
          label: "UserDataMappingLookup",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/userdatamappingsource",
          label: "UserDataMappingSource",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/userdatamappings",
          label: "UserDataMappings",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/userdetail",
          label: "UserDetail",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/usernotificationsettings",
          label: "UserNotificationSettings",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/useroptions",
          label: "UserOptions",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/useroptionslocations",
          label: "UserOptionsLocations",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/uuidlist",
          label: "UuidList",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/validationerror",
          label: "ValidationError",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/viewcolumn",
          label: "ViewColumn",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/viewcolumnoption",
          label: "ViewColumnOption",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/viewdefinition",
          label: "ViewDefinition",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/viewfiltervalue",
          label: "ViewFilterValue",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/viewitemcreateresponse",
          label: "ViewItemCreateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/viewitemgetresponse",
          label: "ViewItemGetResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/viewitemupdateresponse",
          label: "ViewItemUpdateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/viewlistresponse",
          label: "ViewListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/viewschedule",
          label: "ViewSchedule",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/viewsharesummary",
          label: "ViewShareSummary",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/viewsort",
          label: "ViewSort",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/assets/schemas/viewtab",
          label: "ViewTab",
          className: "schema",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
