import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "api/inventory/inventory-api",
    },
    {
      type: "category",
      label: "Actions",
      link: {
        type: "doc",
        id: "api/inventory/inventory-actions",
      },
      items: [
        {
          type: "doc",
          id: "api/inventory/get-inventory-action",
          label: "Get inventory action by ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/inventory/get-inventory-action-post",
          label: "Get inventory action by ID (POST)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/inventory/delete-inventory-action",
          label: "Delete inventory action",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/inventory/query-inventory-actions-get",
          label: "Query inventory actions (GET)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/inventory/query-inventory-actions",
          label: "Query inventory actions",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/inventory/delete-inventory-actions-by-query",
          label: "Delete inventory actions by query",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/inventory/get-inventory-actions-by-ids",
          label: "Get inventory actions by IDs",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/inventory/delete-inventory-actions-by-ids",
          label: "Delete inventory actions by IDs",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/inventory/create-inventory-action",
          label: "Create inventory action",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/inventory/create-inventory-actions-batch",
          label: "Create multiple inventory actions",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/inventory/update-inventory-action",
          label: "Update inventory action",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/inventory/update-inventory-actions-by-query",
          label: "Update inventory actions by query",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/inventory/update-inventory-actions-by-ids",
          label: "Update inventory actions by IDs",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Catalog",
      link: {
        type: "doc",
        id: "api/inventory/inventory-catalog",
      },
      items: [
        {
          type: "doc",
          id: "api/inventory/get-inventory-item-by-id",
          label: "Get inventory catalog item by ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/inventory/get-inventory-item-by-id-post",
          label: "Get inventory catalog item by ID (POST)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/inventory/delete-inventory-item",
          label: "Delete inventory catalog item",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/inventory/query-inventory-items-legacy",
          label: "Query inventory catalog items (legacy GET)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/inventory/query-inventory-items",
          label: "Query inventory catalog items",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/inventory/delete-inventory-items-by-query",
          label: "Delete inventory items by query",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/inventory/get-inventory-items-by-ids",
          label: "Get inventory items by IDs",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/inventory/delete-inventory-items-by-ids",
          label: "Delete inventory items by IDs",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/inventory/create-inventory-item",
          label: "Create inventory catalog item",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/inventory/create-inventory-items-batch",
          label: "Create multiple inventory catalog items",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/inventory/update-inventory-item",
          label: "Update inventory catalog item",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/inventory/update-inventory-items-by-query",
          label: "Update inventory items by query",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/inventory/update-inventory-items-by-ids",
          label: "Update inventory items by IDs",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/inventory/bulk-delete-inventory-items",
          label: "Bulk delete inventory items",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Details",
      link: {
        type: "doc",
        id: "api/inventory/inventory-details",
      },
      items: [
        {
          type: "doc",
          id: "api/inventory/get-inventory-by-id",
          label: "Get inventory stock by ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/inventory/get-inventory-by-id-post",
          label: "Get inventory stock by ID (POST)",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Managing",
      link: {
        type: "doc",
        id: "api/inventory/inventory-managing",
      },
      items: [
        {
          type: "doc",
          id: "api/inventory/create-inventory",
          label: "Create inventory stock record",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/inventory/create-inventories-batch",
          label: "Create multiple inventory stock records",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/inventory/update-inventory",
          label: "Update inventory stock record",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/inventory/update-inventories-by-query",
          label: "Update inventory records by query",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/inventory/update-inventories-by-ids",
          label: "Update multiple inventory records by IDs",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Purchase Orders",
      link: {
        type: "doc",
        id: "api/inventory/inventory-purchase-orders",
      },
      items: [
        {
          type: "doc",
          id: "api/inventory/query-purchase-orders",
          label: "Search purchase orders",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/inventory/get-purchase-order-by-id-inventory",
          label: "Get purchase order by ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/inventory/create-purchase-order-inventory",
          label: "Create purchase order",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/inventory/update-purchase-order-inventory",
          label: "Update purchase order",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Searching",
      link: {
        type: "doc",
        id: "api/inventory/inventory-searching",
      },
      items: [
        {
          type: "doc",
          id: "api/inventory/get-inventory-by-query",
          label: "Query inventory with InventoryId filter",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/inventory/query-inventory-by-id-post",
          label: "Query inventory with InventoryId filter (POST)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/inventory/list-inventories",
          label: "List all inventory stock records",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/inventory/query-inventories",
          label: "Query inventory stock records",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Summaries",
      link: {
        type: "doc",
        id: "api/inventory/inventory-summaries",
      },
      items: [
        {
          type: "doc",
          id: "api/inventory/get-inventory-category-summary",
          label: "Get inventory category summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/inventory/get-inventory-location-category-summary",
          label: "Get inventory location category summary",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Timeline",
      link: {
        type: "doc",
        id: "api/inventory/inventory-timeline",
      },
      items: [
        {
          type: "doc",
          id: "api/inventory/get-inventory-actions-timeline",
          label: "Get inventory actions timeline",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/inventory/get-inventory-actions-timeline-post",
          label: "Get inventory actions timeline (POST)",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Schemas",
      items: [
        {
          type: "doc",
          id: "api/inventory/schemas/bulkdeleteinventoryitemrequest",
          label: "BulkDeleteInventoryItemRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/bulkinventoryitemsdeleterequest",
          label: "BulkInventoryItemsDeleteRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/filtermatch",
          label: "FilterMatch",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/fundingsource",
          label: "FundingSource",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/getinventoriesrequest",
          label: "GetInventoriesRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/getinventoryactionsrequest",
          label: "GetInventoryActionsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/getinventoryitemsrequest",
          label: "GetInventoryItemsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/inventory",
          label: "Inventory",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/inventoryactionbatchdeleteresponse",
          label: "InventoryActionBatchDeleteResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/inventoryactionbatchupdateresponse",
          label: "InventoryActionBatchUpdateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/inventoryactioncreateresponse",
          label: "InventoryActionCreateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/inventoryactionitemresponse",
          label: "InventoryActionItemResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/inventoryactionlistresponse",
          label: "InventoryActionListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/inventoryactionsummary",
          label: "InventoryActionSummary",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/inventoryactionticketsummary",
          label: "InventoryActionTicketSummary",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/inventoryactionupdateresponse",
          label: "InventoryActionUpdateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/inventoryactionusersummary",
          label: "InventoryActionUserSummary",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/inventorybatchcreateresponse",
          label: "InventoryBatchCreateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/inventorybatchupdateresponse",
          label: "InventoryBatchUpdateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/inventorycategoryalertmessage",
          label: "InventoryCategoryAlertMessage",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/inventorycategorychild",
          label: "InventoryCategoryChild",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/inventorycategoryrootmodel",
          label: "InventoryCategoryRootModel",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/inventorycategorysummary",
          label: "InventoryCategorySummary",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/inventorycategorysummaryresponse",
          label: "InventoryCategorySummaryResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/inventorycreateresponse",
          label: "InventoryCreateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/inventorydeleteresponse",
          label: "InventoryDeleteResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/inventoryitembatchcreateresponse",
          label: "InventoryItemBatchCreateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/inventoryitembatchdeleteresponse",
          label: "InventoryItemBatchDeleteResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/inventoryitembatchupdateresponse",
          label: "InventoryItemBatchUpdateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/inventoryitembulkdeleteresponse",
          label: "InventoryItemBulkDeleteResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/inventoryitemcreateresponse",
          label: "InventoryItemCreateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/inventoryitemcustomfieldvalue",
          label: "InventoryItemCustomFieldValue",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/inventoryitemdetail",
          label: "InventoryItemDetail",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/inventoryitemgetresponse",
          label: "InventoryItemGetResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/inventoryitemlistgetresponse",
          label: "InventoryItemListGetResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/inventoryitemrequestfilter",
          label: "InventoryItemRequestFilter",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/inventoryitemsummary",
          label: "InventoryItemSummary",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/inventoryitemupdateresponse",
          label: "InventoryItemUpdateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/inventorylistgetresponse",
          label: "InventoryListGetResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/inventorylocationcategorychild",
          label: "InventoryLocationCategoryChild",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/inventorylocationcategoryrootmodel",
          label: "InventoryLocationCategoryRootModel",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/inventorylocationcategorysummaryresponse",
          label: "InventoryLocationCategorySummaryResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/inventorylocationsummary",
          label: "InventoryLocationSummary",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/inventorypagingoptions",
          label: "InventoryPagingOptions",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/inventoryrequestfilter",
          label: "InventoryRequestFilter",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/inventorystockdetailresponse",
          label: "InventoryStockDetailResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/inventorystockentry",
          label: "InventoryStockEntry",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/inventorytimelineentry",
          label: "InventoryTimelineEntry",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/inventorytimelinelistresponse",
          label: "InventoryTimelineListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/inventoryupdateresponse",
          label: "InventoryUpdateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/itemgetresponse",
          label: "ItemGetResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/itemupdateresponse",
          label: "ItemUpdateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/listdeleteresponse",
          label: "ListDeleteResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/listgetresponse",
          label: "ListGetResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/listupdateresponse",
          label: "ListUpdateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/pagingmetadata",
          label: "PagingMetadata",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/pagingoptions",
          label: "PagingOptions",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/pagingresponse",
          label: "PagingResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/partsearchfacetkey",
          label: "PartSearchFacetKey",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/purchaseorder",
          label: "PurchaseOrder",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/purchaseorderitemcreateresponse",
          label: "PurchaseOrderItemCreateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/purchaseorderitemgetresponse",
          label: "PurchaseOrderItemGetResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/purchaseorderitemupdateresponse",
          label: "PurchaseOrderItemUpdateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/purchaseorderlistgetresponse",
          label: "PurchaseOrderListGetResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/purchaseorderstatustype",
          label: "PurchaseOrderStatusType",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/purchaseordertype",
          label: "PurchaseOrderType",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/responseenvelope",
          label: "ResponseEnvelope",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/responselog",
          label: "ResponseLog",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/simpleuser",
          label: "SimpleUser",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/softvalidationerror",
          label: "SoftValidationError",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/sortoptions",
          label: "SortOptions",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/supplier",
          label: "Supplier",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/timelineentryticket",
          label: "TimelineEntryTicket",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/updateinventoriesrequest",
          label: "UpdateInventoriesRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/updateinventoryactionrequest",
          label: "UpdateInventoryActionRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/updateinventoryactionsrequest",
          label: "UpdateInventoryActionsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/updateinventoryitemrequest",
          label: "UpdateInventoryItemRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/updateinventoryitemsrequest",
          label: "UpdateInventoryItemsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/inventory/schemas/updateinventoryrequest",
          label: "UpdateInventoryRequest",
          className: "schema",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
