import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "api/categories/categories-api",
    },
    {
      type: "category",
      label: "Bulk",
      link: {
        type: "doc",
        id: "api/categories/categories-bulk",
      },
      items: [
        {
          type: "doc",
          id: "api/categories/bulk-set-category-popularity",
          label: "Bulk set category popularity",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/categories/bulk-delete-categories",
          label: "Bulk delete categories",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Listing",
      link: {
        type: "doc",
        id: "api/categories/categories-listing",
      },
      items: [
        {
          type: "doc",
          id: "api/categories/list-model-categories",
          label: "List model categories",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/categories/list-app-categories",
          label: "List app categories",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/categories/list-filter-categories",
          label: "List filter categories",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/categories/list-asset-categories",
          label: "List asset categories",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/categories/list-kb-categories",
          label: "List knowledge base categories",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/categories/list-issue-categories",
          label: "List issue categories",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/categories/list-role-categories",
          label: "List role categories",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/categories/list-wizard-categories",
          label: "List ticket wizard categories",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Managing",
      link: {
        type: "doc",
        id: "api/categories/categories-managing",
      },
      items: [
        {
          type: "doc",
          id: "api/categories/create-category",
          label: "Create a new category",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/categories/update-category",
          label: "Update a category",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/categories/delete-category",
          label: "Delete a category",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/categories/undelete-category",
          label: "Restore a deleted category",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/categories/set-category-sort-order",
          label: "Set category sort order",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/categories/create-model-category",
          label: "Create a model category",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/categories/create-issue-category",
          label: "Create an issue category",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/categories/create-asset-category",
          label: "Create an asset category",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/categories/create-kb-category",
          label: "Create a knowledge base category",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/categories/create-role-category",
          label: "Create a role category",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Retrieval",
      link: {
        type: "doc",
        id: "api/categories/categories-retrieval",
      },
      items: [
        {
          type: "doc",
          id: "api/categories/get-category-by-id",
          label: "Get category by ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/categories/get-category-by-id-and-type",
          label: "Get category by ID and type",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/categories/get-category-entity-type-links",
          label: "Get category-entity type links",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Searching",
      link: {
        type: "doc",
        id: "api/categories/categories-searching",
      },
      items: [
        {
          type: "doc",
          id: "api/categories/search-categories-v-1",
          label: "Search categories (V1)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/categories/list-categories-v-2",
          label: "List categories (V2)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/categories/search-categories-v-2",
          label: "Search categories (V2)",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Suggestions",
      link: {
        type: "doc",
        id: "api/categories/categories-suggestions",
      },
      items: [
        {
          type: "doc",
          id: "api/categories/get-suggested-categories-for-user",
          label: "Get suggested categories for user",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/categories/get-suggested-online-systems-for-user",
          label: "Get suggested online systems for user",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/categories/get-popular-categories-for-roles",
          label: "Get popular categories for roles",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "App Links",
      link: {
        type: "doc",
        id: "api/categories/categories-app-links",
      },
      items: [
        {
          type: "doc",
          id: "api/categories/list-categories-for-app",
          label: "List categories for an app",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/categories/list-app-category-links",
          label: "List app-category links",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/categories/link-category-to-app",
          label: "Link category to app",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/categories/unlink-category-from-app",
          label: "Unlink category from app",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Schemas",
      items: [
        {
          type: "doc",
          id: "api/categories/schemas/actionresponse",
          label: "ActionResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/categories/schemas/address",
          label: "Address",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/categories/schemas/appcategorylink",
          label: "AppCategoryLink",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/categories/schemas/asset",
          label: "Asset",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/categories/schemas/assetcategorysummary",
          label: "AssetCategorySummary",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/categories/schemas/assetcustomfieldvalue",
          label: "AssetCustomFieldValue",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/categories/schemas/assetdatamappinglookup",
          label: "AssetDataMappingLookup",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/categories/schemas/assetdatamappingsource",
          label: "AssetDataMappingSource",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/categories/schemas/assetdatamappings",
          label: "AssetDataMappings",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/categories/schemas/assetmanufacturersummary",
          label: "AssetManufacturerSummary",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/categories/schemas/assetmodelsummary",
          label: "AssetModelSummary",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/categories/schemas/assetownersummary",
          label: "AssetOwnerSummary",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/categories/schemas/assetstatussummary",
          label: "AssetStatusSummary",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/categories/schemas/assettotalcost",
          label: "AssetTotalCost",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/categories/schemas/assetvaluation",
          label: "AssetValuation",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/categories/schemas/assetvaluationperiod",
          label: "AssetValuationPeriod",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/categories/schemas/bulkcategorypopularityrequest",
          label: "BulkCategoryPopularityRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/categories/schemas/bulkdeletecategoriesresponse",
          label: "BulkDeleteCategoriesResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/categories/schemas/bulkdeletecategoryrequest",
          label: "BulkDeleteCategoryRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/categories/schemas/bulkdeletecategoryrequestwrapper",
          label: "BulkDeleteCategoryRequestWrapper",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/categories/schemas/bulksetcategorypopularityresponse",
          label: "BulkSetCategoryPopularityResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/categories/schemas/category",
          label: "Category",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/categories/schemas/categorycreaterequest",
          label: "CategoryCreateRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/categories/schemas/categoryfilter",
          label: "CategoryFilter",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/categories/schemas/categoryitemresponse",
          label: "CategoryItemResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/categories/schemas/categorylistresponse",
          label: "CategoryListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/categories/schemas/categorytypeentitytypelink",
          label: "CategoryTypeEntityTypeLink",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/categories/schemas/complexeditorvalues",
          label: "ComplexEditorValues",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/categories/schemas/createcategoryresponse",
          label: "CreateCategoryResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/categories/schemas/customfieldeditortypeid",
          label: "CustomFieldEditorTypeId",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/categories/schemas/customfieldtypedetail",
          label: "CustomFieldTypeDetail",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/categories/schemas/datafilter",
          label: "DataFilter",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/categories/schemas/datafilteroperations",
          label: "DataFilterOperations",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/categories/schemas/filtercategory",
          label: "FilterCategory",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/categories/schemas/filtercategorylistresponse",
          label: "FilterCategoryListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/categories/schemas/forbiddenerror",
          label: "ForbiddenError",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/categories/schemas/getcategoriesrequest",
          label: "GetCategoriesRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/categories/schemas/getcategoriesrequestv-1",
          label: "GetCategoriesRequestV1",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/categories/schemas/getcategoryentitytypelinksresponse",
          label: "GetCategoryEntityTypeLinksResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/categories/schemas/getentityrequest",
          label: "GetEntityRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/categories/schemas/getpopularcategoriesforrolesresponse",
          label: "GetPopularCategoriesForRolesResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/categories/schemas/getsuggestedonlinesystemsforuserresponse",
          label: "GetSuggestedOnlineSystemsForUserResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/categories/schemas/itemcreateresponse",
          label: "ItemCreateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/categories/schemas/itemdeleteresponse",
          label: "ItemDeleteResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/categories/schemas/itemgetresponse",
          label: "ItemGetResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/categories/schemas/iteminuseerror",
          label: "ItemInUseError",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/categories/schemas/itemupdateresponse",
          label: "ItemUpdateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/categories/schemas/kbcategory",
          label: "KbCategory",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/categories/schemas/listappcategorylinksresponse",
          label: "ListAppCategoryLinksResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/categories/schemas/listgetresponse",
          label: "ListGetResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/categories/schemas/listkbcategoriesresponse",
          label: "ListKbCategoriesResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/categories/schemas/location",
          label: "Location",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/categories/schemas/locationcustomfieldvalue",
          label: "LocationCustomFieldValue",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/categories/schemas/locationstatustype",
          label: "LocationStatusType",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/categories/schemas/locationtype",
          label: "LocationType",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/categories/schemas/modelcategory",
          label: "ModelCategory",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/categories/schemas/modelcategorylistresponse",
          label: "ModelCategoryListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/categories/schemas/notfounderror",
          label: "NotFoundError",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/categories/schemas/pagingmetadata",
          label: "PagingMetadata",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/categories/schemas/pagingoptions",
          label: "PagingOptions",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/categories/schemas/requestoptions",
          label: "RequestOptions",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/categories/schemas/site",
          label: "Site",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/categories/schemas/softvalidationerror",
          label: "SoftValidationError",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/categories/schemas/sortoptions",
          label: "SortOptions",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/categories/schemas/unauthorizederror",
          label: "UnauthorizedError",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/categories/schemas/updatecategoryresponse",
          label: "UpdateCategoryResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/categories/schemas/uuidlist",
          label: "UuidList",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/categories/schemas/validationerror",
          label: "ValidationError",
          className: "schema",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
